feat: new getLog task
kestra-io/kestra pull request #1059
Opened 2023-03-13 09:25 UTC by Skraye

2023-03-13 09:54 UTC, loicmathieu requested changes
Maybe add a metric with the number of lines.

2023-03-13 09:54 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/tasks/debugs/GetLog.java
> +public class GetLog extends Task implements RunnableTask<GetLog.Output> {
Will be better named `Fetch`

2023-03-13 09:54 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/tasks/debugs/GetLog.java
> +                logs.addAll(runContext.getApplicationContext().getBean(LogRepositoryInterface.class).findByExecutionIdAndTaskId(executionId, taskId, level));
Don't get the bean each time as it can be time consuming.
Get the bean once out of the if/else block.

2023-03-13 09:54 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/tasks/debugs/GetLog.java
> +    @PluginProperty(dynamic = true)
I don't think it should be dynamic as task IDs are static inside the flow definition.

2023-03-13 16:22 UTC, tchiotludo requested changes

2023-03-13 16:22 UTC, tchiotludo commented on core/src/main/java/io/kestra/core/tasks/debugs/Fetch.java
> +public class Fetch extends Task implements RunnableTask<Fetch.Output> {
You need to support the `executionId` like in Email or [Slack Notification](https://github.com/kestra-io/plugin-notifications/blob/a4d72de4eac6cee01e6d59d748eb795ce063749b/src/main/java/io/kestra/plugin/notifications/slack/SlackExecution.java#L55).
People use trigger flows for notification most of the time, and they want to get the log from an previous execution.

2023-03-13 16:22 UTC, tchiotludo commented on core/src/main/java/io/kestra/core/tasks/debugs/Fetch.java
> +        List<LogEntry> logs = new ArrayList<>();
You are mounting the full log in memory with this, you need to flush the data directly on the filesystems

2023-03-13 16:22 UTC, tchiotludo commented on core/src/main/java/io/kestra/core/tasks/debugs/Fetch.java
> +        if(this.tasksId != null){
Best is to used the `find(` to avoid mounting the whole data in memory

2023-03-15 09:21 UTC, loicmathieu requested changes

2023-03-15 10:46 UTC, Skraye commented on build.gradle
> +        dependsOn = [':ui:assembleFrontend']
Probably leftover of this : https://github.com/kestra-io/kestra/pull/1059/commits/f4e378c8af62b6d76a0e763cfe4ae20e9f07ab1f

2023-03-16 16:59 UTC, merged