fix: Doc generation now takes the NotNull field from interface methods
kestra-io/kestra pull request #1211
Opened 2023-04-28 11:20 UTC by brian-mulier-p

2023-04-28 11:29 UTC, tchiotludo requested changes

2023-04-28 11:29 UTC, tchiotludo commented on core/src/main/java/io/kestra/core/docs/JsonSchemaGenerator.java
> +                JavaxValidationOption.NOT_NULLABLE_METHOD_IS_REQUIRED,
maybe a little unit test ? to validate future non regression ?

2023-05-02 07:36 UTC, loicmathieu approved these changes
LGTM

2023-05-02 07:36 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/docs/ClassPluginDocumentation.java
> +            if(key1Required == key2Required) return key1.compareTo(key2);
As it's boolean it's more logical to use `&&` instead of `==` but you can keep it if you want.

2023-05-05 09:07 UTC, merged