feat:(): Flow Metrics aggregation backend
kestra-io/kestra pull request #1226
Opened 2023-05-04 08:17 UTC by Skraye

2023-05-04 08:56 UTC, loicmathieu requested changes

2023-05-04 08:56 UTC, loicmathieu commented on webserver/src/main/java/io/kestra/webserver/controllers/MetricController.java
> +    public ArrayListTotal<MetricStat> aggregateByFlowId(
You will not paginate so I think an ArrayList is enought

2023-05-04 08:56 UTC, loicmathieu commented on jdbc/src/main/java/io/kestra/jdbc/repository/AbstractJdbcMetricRepository.java
> +    private List<MetricStat> query(
```suggestion
    private List<MetricStat> aggregate(
```

2023-05-04 08:56 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/repositories/MetricRepositoryInterface.java
> +    ArrayListTotal<MetricEntry> aggregateByFlowIdAndTaskId(String flowId, String taskId);
```suggestion
    ArrayListTotal<MetricStat> aggregateByFlowIdAndTaskId(String flowId, String taskId);
```

2023-05-05 10:25 UTC, loicmathieu requested changes

2023-05-05 10:25 UTC, loicmathieu commented on webserver/src/main/java/io/kestra/webserver/controllers/MetricController.java
> +    @Operation(tags = {"Metrics"}, summary = "Get metrics for a specific flow")
```suggestion
    @Operation(tags = {"Metrics"}, summary = "Get metric names for a specific flow")
```

2023-05-05 10:25 UTC, loicmathieu commented on webserver/src/main/java/io/kestra/webserver/controllers/MetricController.java
> +    @Operation(tags = {"Metrics"}, summary = "Get metrics for a specific task in a flow")
```suggestion
    @Operation(tags = {"Metrics"}, summary = "Get metric names for a specific task in a flow")
```

2023-05-05 10:25 UTC, loicmathieu commented on webserver/src/main/java/io/kestra/webserver/controllers/MetricController.java
> +    @Operation(tags = {"Metrics"}, summary = "Get metrics for a specific flow")
```suggestion
    @Operation(tags = {"Metrics"}, summary = "Get metric aggregations for a specific flow")
```

2023-05-05 10:25 UTC, loicmathieu commented on webserver/src/main/java/io/kestra/webserver/controllers/MetricController.java
> +        @Parameter(description = "The type of aggregation") @QueryValue(defaultValue = "sum") String aggregation
```suggestion
        @Parameter(description = "The type of aggregation: avg, sum, min or max") @QueryValue(defaultValue = "sum") String aggregation
```

2023-05-05 10:25 UTC, loicmathieu commented on webserver/src/main/java/io/kestra/webserver/controllers/MetricController.java
> +    @Operation(tags = {"Metrics"}, summary = "Get metrics for a specific flow")
```suggestion
    @Operation(tags = {"Metrics"}, summary = "Get metricagregations for a specific flow")
```

2023-05-05 10:25 UTC, loicmathieu commented on webserver/src/main/java/io/kestra/webserver/controllers/MetricController.java
> +        @Parameter(description = "The type of aggregation") @QueryValue(defaultValue = "sum") String aggregation
```suggestion
        @Parameter(description = "The type of aggregation: avg, sum, min or max") @QueryValue(defaultValue = "sum") String aggregation
```

2023-05-11 08:41 UTC, loicmathieu requested changes

2023-05-11 08:41 UTC, loicmathieu commented on webserver/src/main/java/io/kestra/webserver/controllers/MetricController.java
> +    @Get(uri = "/flow/{namespace}/{flowId}/{metric}", produces = MediaType.TEXT_JSON)
```suggestion
    @Get(uri = "/aggregates/{namespace}/{flowId}/{metric}", produces = MediaType.TEXT_JSON)
```

2023-05-11 08:41 UTC, loicmathieu commented on webserver/src/main/java/io/kestra/webserver/controllers/MetricController.java
> +    @Get(uri = "/flow/{namespace}/{flowId}/task/{taskId}/{metric}", produces = MediaType.TEXT_JSON)
```suggestion
    @Get(uri = "/aggregates/{namespace}/{flowId}/{taskId}/{metric}", produces = MediaType.TEXT_JSON)
```

2023-05-11 12:45 UTC, Skraye commented
close #1226

2023-05-12 21:10 UTC, merged