fix(core): allow usage of Pebble verbatim tag in our recursive renderer
kestra-io/kestra pull request #1267
Opened 2023-05-10 15:58 UTC by loicmathieu

close #1244

After investigation, due to the fact that we render a template recursively, we cannot use an operator like `\{{` nor a function, nor a filter :(

I ended up using a hack to stop the recursivity if using the verbatim tag that is the tag that should have been working for this. Inline verbatim is not possible.

More advanced solutions (function, tag, filter) would need to hook into the template engine itself as at the render level we only have access to the template and its result.

Another solution would be to stop inline rendering and provide a `render` function so users opt-in for recursive rendering.

I'm not very happy with the solution so if someone has a better idea I'm open to suggestions.

2023-05-10 16:06 UTC, tchiotludo requested changes
verbatim could work for me, and we need to find a syntax that is not `{{` or `{%`, and don't think we could trick on that since even the author of pebble had to trick

2023-05-10 16:06 UTC, tchiotludo commented on core/src/main/java/io/kestra/core/runners/VariableRenderer.java
> +    private boolean isVerbatim(String inline) {
will only work with a raw starting with `{%verbatim` and will failed with `content{%verbatim` that is a must have.

2023-05-11 09:32 UTC, loicmathieu commented
@tchiotludo I had a new lightweight idea to replace `\{{` and `\}}`  with an escape sequence and replace back at the end.
It's an easy solution that at least allow to display `{{` without too many modification.
We can use another replace sequence that the one I propose here, the PR is just a demo to know if you think it would be acceptable.

2023-05-16 20:33 UTC, tchiotludo commented
close in favor of this one https://github.com/kestra-io/kestra/pull/1316

2023-05-16 20:33 UTC, closed without merging