fix/error-message-on-draft-save
kestra-io/kestra pull request #1404
Opened 2023-05-25 09:31 UTC by brian-mulier-p

closes #1341

2023-05-25 10:35 UTC, Skraye requested changes
Please use the error toast that shows the error in a code block. However, long error messages are not very readable

Else, LGTM

2023-05-29 06:51 UTC, tchiotludo commented
@brian-mulier-p can you make the change quickly please?

2023-05-29 07:49 UTC, brian-mulier-p commented
fixed

2023-05-29 08:05 UTC, Skraye approved these changes

2023-05-29 08:12 UTC, merged