feat/default-flow-creation-template
kestra-io/kestra pull request #1554
Opened 2023-06-19 15:39 UTC by brian-mulier-p

closes #1271

2023-06-20 15:31 UTC, Skraye requested changes

2023-06-21 07:39 UTC, brian-mulier-p commented on ui/src/components/graph/nodes/Edge.vue
> +            [..."hello"].
Oups, I was testing something, good spot :+1:

2023-06-21 07:45 UTC, Skraye commented on ui/src/components/graph/nodes/Edge.vue
> +            [..."hello"].
I don't have the issue; maybe you have some dependencies that are not up to date?

2023-06-21 07:50 UTC, brian-mulier-p commented on ui/src/components/inputs/EditorView.vue
> +        if (validationErrors) {
I feel like we weren't handling that case unless in creation mode. Is that intended ? Should we create another issue ? We may need to add another validate then or should we simply call fetchGraph and handle the error case ?

2023-06-21 07:50 UTC, brian-mulier-p commented on ui/src/components/graph/nodes/Edge.vue
> +            [..."hello"].
I just npm installed and still have the issue, looks strange :thinking:

2023-06-21 07:51 UTC, brian-mulier-p commented on ui/src/components/graph/nodes/Edge.vue
> +            [..."hello"].
I guess I will try to live along this compiler error

2023-06-21 20:22 UTC, merged