Fix/readonly deleted flow
kestra-io/kestra pull request #2152
Opened 2023-09-20 15:40 UTC by Skraye

close #2012

2023-09-22 07:33 UTC, Skraye commented
close #2147

2023-09-22 08:06 UTC, brian-mulier-p commented
It lacks some padding for it to be pretty + misses a space between the warning icon & the text
![image](https://github.com/kestra-io/kestra/assets/37618489/fbea70e3-b107-4969-9843-670038c93daf)

2023-09-22 08:07 UTC, brian-mulier-p commented
Please also update the flowYaml from editor and remove the deleted true as you do it only when sending the flow payload to backend for restore but user keeps the deleted: true in its yaml

2023-09-22 08:07 UTC, brian-mulier-p requested changes
Not much to change :+1:

2023-09-22 08:12 UTC, Skraye commented on ui/src/components/inputs/EditorView.vue
> +        },
isTopoOnly is the old readOnly, which in fact was just showing only the topo as read-only and people couldn't watch source code

2023-09-22 08:13 UTC, brian-mulier-p commented
Restoring a flow doesn't change the readonly prop ence we still cannot edit back the flow
![image](https://github.com/kestra-io/kestra/assets/37618489/42391467-251a-4acc-8e9e-e0a2909e2d89)

2023-09-22 08:15 UTC, Skraye commented on ui/src/stores/flow.js
> +                    }
Does it need big changes ? I can just fix that conflict in my PR 
However this is wrong `(!options.store)` because it make store to false by default

2023-09-22 08:24 UTC, brian-mulier-p commented on ui/src/stores/flow.js
> +                    }
Yes you're true for the !options.store, keep it as is
For the needed changes, there is two things: all the loadFlowNoCommit calls should be replaced with the loadFlow & options.store = false
same applies with revisions and I think that's it (search for "NoCommit" methods)

2023-09-22 08:34 UTC, brian-mulier-p commented
You miss a test for the newly introduced "deleted fetch"

2023-09-22 09:19 UTC, brian-mulier-p commented
According to Figma the message should be way smaller (even above the Flow name but I can understand why you didn't do it :laughing:)

2023-09-22 09:34 UTC, brian-mulier-p commented
You miss a bunch of places where to add the allowDeleted I think:
- ExecutionRoot
- TriggerFlow

2023-09-25 12:43 UTC, brian-mulier-p approved these changes
LGTM except isTopoOnly which is useless

2023-09-25 12:54 UTC, brian-mulier-p requested changes
Please remove isTopoOnly flag as it's pointless + we're getting 404 in console when fetching flow in logs tab (and topo of execution) leading to undisplayed task icons

2023-09-26 07:50 UTC, merged