fix(): better dashboard responsiveness
kestra-io/kestra pull request #2185
Opened 2023-09-26 09:34 UTC by Skraye

Did reduce the police size as with the breaking text is was rendering really weird and happening with not this high number.

close #1563

2023-09-26 10:25 UTC, brian-mulier-p requested changes
I don't think this is the proper way to  handle it :/
See this screen with not that small width and it still occurs
![image](https://github.com/kestra-io/kestra/assets/37618489/79351cf8-72b2-460e-9343-eb4416b74fec)

I suggest to use `flex-wrap: wrap` + remove `margins` in favor of `gap` property

2023-09-26 10:45 UTC, Skraye commented
Added flex-wrap to avoid this

2023-09-26 10:49 UTC, tchiotludo commented
already done here : https://github.com/kestra-io/kestra/pull/2184

2023-09-27 14:16 UTC, brian-mulier-p requested changes

2023-09-27 14:16 UTC, brian-mulier-p commented on ui/src/components/home/HomeSummaryStatusLabel.vue
> +            <div v-if="count > 0" :key="status" class="d-flex justify-content-around mb-2 flex-wrap">
Please remove any mb / me & use 
```
column-gap: calc(var(--spacer) * 1.5);
row-gap: calc(var(--spacer) / 2);
```

2023-09-27 15:40 UTC, brian-mulier-p approved these changes
LGTM

2023-09-28 07:03 UTC, merged