feat/new-header
kestra-io/kestra pull request #2286
Opened 2023-10-12 06:37 UTC by brian-mulier-p

2023-10-16 08:12 UTC, anna-geller commented
Can you add a screenshot @brian-mulier-p?

2023-10-16 08:34 UTC, brian-mulier-p commented
![image](https://github.com/kestra-io/kestra/assets/37618489/8581ea39-25ab-4d2a-babc-dc9b2da59334)
![image](https://github.com/kestra-io/kestra/assets/37618489/e50b8c77-84b6-46f9-8930-63aebe9920bf)

Note that there is some mismatch with Figma as we have to rework colors not to require exceptions specifically for the header, colors should be synced between Figma & UI so the colors match naturally. I reverted any exception around it after asking @tchiotludo how to handle it.

2023-10-16 09:08 UTC, anna-geller commented
Nice! we need to add one more option here "Execute with labels"
![image](https://github.com/kestra-io/kestra/assets/86264395/2008df4f-7c86-4d75-91af-da896465f949)

And cut the labels here:

![image](https://github.com/kestra-io/kestra/assets/86264395/6f43eac2-bc50-4f1e-b30b-a17e83bcd491)

2023-10-16 09:14 UTC, brian-mulier-p commented
I think that's another subject :+1: Can you create an issue if there is none ? This PR will already be huge so it shouldn't be  included it there

2023-10-16 09:26 UTC, anna-geller commented
assigned to you :) https://github.com/kestra-io/kestra/issues/2173

2023-10-16 12:28 UTC, anna-geller commented on ui/src/components/flows/TriggerFlow.vue
>              {{ $t('New execution') }}
```suggestion
            {{ $t('Execute') }}
```

2023-10-17 09:51 UTC, anna-geller commented
Discussed some change requests via Slack:

1. Move the `"Successfull saved"` popup to the bottom as it currently covers the Execute button.
2. In a separate issue, we will tackle the Execute button to allow `Execute with labels` and only show the popup to add Execution labels when user clicks on that second option to execute with labels -- see issue https://github.com/kestra-io/kestra/issues/2173#issuecomment-1764390375 
3. The Import and Source Search both need to be added as independent actions in the Flows menu rather than hidden behind Actions

currently is:
![image](https://github.com/kestra-io/kestra/assets/86264395/32583fc3-a423-492c-afb6-5682cb6dbe51)

should be:
![image](https://github.com/kestra-io/kestra/assets/86264395/b4a5b9b9-7cd5-4f7a-ab3d-2959144eb0f0)

4. Also for the Flows page - when you open the Editor tab, the Save and Actions menu should ideally be added to the main menu if possible rather than within the Editor tab (might also be easier with VS Code later on - WDYT @brian-mulier-p?)

![image](https://github.com/kestra-io/kestra/assets/86264395/18778291-3244-4715-8887-9a292fc60119)

5. For all tabs within the Executions page, there menus should also be directly visible rather than hidden behind Actions:

currently is:
![image](https://github.com/kestra-io/kestra/assets/86264395/f1628365-0098-4010-8117-db7f1bf7b855)

should be:
![image](https://github.com/kestra-io/kestra/assets/86264395/dd76ba6a-1260-48cd-9446-8fd1e62eb63f)

2023-10-17 09:51 UTC, anna-geller requested changes
Discussed some change requests via Slack:

- [x] Move the `"Successfull saved"` popup to the bottom as it currently covers the Execute button.
- [x] In a separate issue, we will tackle the Execute button to allow `Execute with labels` and only show the popup to add Execution labels when user clicks on that second option to execute with labels -- see issue https://github.com/kestra-io/kestra/issues/2173#issuecomment-1764390375 
- [x] The Import and Source Search both need to be added as independent actions in the Flows menu rather than hidden behind Actions

currently is:
![image](https://github.com/kestra-io/kestra/assets/86264395/32583fc3-a423-492c-afb6-5682cb6dbe51)

should be:
![image](https://github.com/kestra-io/kestra/assets/86264395/b4a5b9b9-7cd5-4f7a-ab3d-2959144eb0f0)

- [x] Also for the Flows page - when you open the Editor tab, the Save and Actions menu should ideally be added to the main menu if possible rather than within the Editor tab (might also be easier with VS Code later on - WDYT @brian-mulier-p?)

![image](https://github.com/kestra-io/kestra/assets/86264395/18778291-3244-4715-8887-9a292fc60119)

- [x]  For all tabs within the Executions page, there menus should also be directly visible rather than hidden behind Actions:

currently is:
![image](https://github.com/kestra-io/kestra/assets/86264395/f1628365-0098-4010-8117-db7f1bf7b855)

should be:
![image](https://github.com/kestra-io/kestra/assets/86264395/dd76ba6a-1260-48cd-9446-8fd1e62eb63f)

2023-10-17 09:57 UTC, anna-geller commented
list of follow-up issues that are out-of-scope in this PR https://github.com/kestra-io/kestra/issues/2322

2023-10-17 11:59 UTC, Skraye requested changes
Missing space when clicking source search: 
![image](https://github.com/kestra-io/kestra/assets/37600690/bdc07ed7-3332-428b-947f-e98f21485237)

Flow view > Components seems a bit too big and we have a useless scroll (appear on all tab that goes to bottom):
![image](https://github.com/kestra-io/kestra/assets/37600690/bd68126e-c3fb-4394-ad3d-593ab6a7df51)

Should be same colors, no hovers on 2 first icons
![image](https://github.com/kestra-io/kestra/assets/37600690/0a883b9e-0b6e-48f9-85d2-4033e0da21b4)

You can use the shortcut, write, but not select with enter, you must click, so feature become useless:
![image](https://github.com/kestra-io/kestra/assets/37600690/3ec50f4c-5f78-4b5b-ae99-787a8a6fb520)

execution page : 
![image](https://github.com/kestra-io/kestra/assets/37600690/b4ed58a3-7d0f-47c6-8dc0-213e475f7281)

Arriving on blueprint page when you had already search something:
![image](https://github.com/kestra-io/kestra/assets/37600690/c1a7e04a-5218-4a34-839d-608ea385585a)

2023-10-17 12:34 UTC, brian-mulier-p commented
@anna-geller
4. Discussed with Ludo already, hierarchically there is no way without big hack to do what's asked that's why those buttons were added there: it is way too bound to the editor tab (you can edit the source code from those buttons). Idk when and how we will tackle but this is the proper way to do it right now (seen with @Nico-Kestra & @tchiotludo).
5. Please confirm with @tchiotludo, I've been asking what to do and he told me at first to keep only 1 or 2 main buttons and add a dropdown for further actions to prevent having to handle overflow and lower res. as it's a bit complex from @Nico-Kestra design (the 3 dots only on lower res would imply a lot of duplication or a big hack).

@Skraye
will look at all but:

> You can use the shortcut, write, but not select with enter, you must click, so feature become useless:
This is intended, right now you have a fake search which will later be extended to executions & flows. This will be tackled when it will be done as it will then provide a true value. For now this fake search is kind of a placeholder so I didn't take time to handle this keyboard-only navigation

2023-10-17 14:14 UTC, anna-geller approved these changes
Great work! all issues addressed ✅ 

![image](https://github.com/kestra-io/kestra/assets/86264395/ed7c4fb6-c66c-4f92-9849-034749690c4b)

2023-10-17 14:38 UTC, brian-mulier-p commented
Just found out that the welcome screen looks ugly as we don't have any header and by default there is no margin, will fix that

2023-10-17 15:50 UTC, Skraye commented
Small issue :
![image](https://github.com/kestra-io/kestra/assets/37600690/79bcd913-9cab-40d6-92b3-a641a1d57907)

Those two buttons do the same things; maybe one should be removed? 
![image](https://github.com/kestra-io/kestra/assets/37600690/24b0bfb2-95fe-4bca-8af2-4dbeba2d9d7d)

2023-10-17 16:00 UTC, anna-geller commented
> Small issue : ![image](https://user-images.githubusercontent.com/37600690/275897079-79bcd913-9cab-40d6-92b3-a641a1d57907.png)
> 
> Those two buttons do the same things; maybe one should be removed? ![image](https://user-images.githubusercontent.com/37600690/275897254-24b0bfb2-95fe-4bca-8af2-4dbeba2d9d7d.png)

Great point Yann. We did that deliberately for 2 reasons:
1. For the SaaS version, Live help can point to a different channel in the future e.g. AI chatbot
2. Emmanuel considered it important to show users they can get unblocked and get help when they are stuck.

let's keep both but good observation 👍

2023-10-17 16:17 UTC, brian-mulier-p commented
I asked the same thing to Nico :P

2023-10-17 16:19 UTC, Skraye approved these changes
trivial matter, LGTM

2023-10-17 16:21 UTC, Nico-Kestra commented
<img width="807" alt="Capture d’écran 2023-10-17 à 18 21 11" src="https://github.com/kestra-io/kestra/assets/125994028/0c8b0821-555d-4e87-a684-d344e2d705e5">

2023-10-17 16:34 UTC, brian-mulier-p commented on ui/src/components/executions/ExecutionRoot.vue
> +                                <a class="el-dropdown-menu__item d-flex gap-2" :href="`${finalApiUrl}/executions/${execution.id}`" target="_blank">
![image](https://github.com/kestra-io/kestra/assets/37618489/9759a6cb-cbc2-4194-aa54-1b5eeecdbe57)
No that's a wider dropdown issue (already present). Will not fix it there, we have to apply some styling to dropdown to handle it globally

2023-10-17 17:01 UTC, brian-mulier-p commented
> Just found out that the welcome screen looks ugly as we don't have any header and by default there is no margin, will fix that

Fixed

2023-10-17 17:33 UTC, merged

2023-10-18 07:00 UTC, Nico-Kestra commented
<img width="2042" alt="Capture d’écran 2023-10-18 à 08 59 13" src="https://github.com/kestra-io/kestra/assets/125994028/678e2c2e-51e7-4762-9f6e-fd9bb6935b9b">
Shift the app so that the purple band is not above the menu.