feat(jdbc): add indices on tenant_id
kestra-io/kestra pull request #2408
Opened 2023-10-30 09:44 UTC by loicmathieu

Only add a new index for optimizing findAll(), other access should use existing indices.

The rational is that:
- There should not be a lot of tenants in an instance (a few tens or hundreds at most)
- Existing indices will still be highly distributed as the same flow/namespace has low chance to be on multiple tenants
So the cost of updating all indexes (which means reindexing potentially large tables) with the new columns seems too high with respect to the added value.

2023-11-01 21:37 UTC, tchiotludo commented
We should not add a new index but alter the current one, example : 
```sql
CREATE INDEX IF NOT EXISTS flows_namespace ON flows (deleted, namespace);
```
should be 
```sql
CREATE INDEX IF NOT EXISTS flows_namespace ON flows (deleted, tenant_id, namespace);
```

2023-11-01 21:38 UTC, tchiotludo requested changes
We should not add a new index but alter the current one, example : 
```sql
CREATE INDEX IF NOT EXISTS flows_namespace ON flows (deleted, namespace);
```
should be 
```sql
CREATE INDEX IF NOT EXISTS flows_namespace ON flows (deleted, tenant_id, namespace);
```

2023-11-02 17:12 UTC, loicmathieu commented
@tchiotludo I updated all indices except those who have execution_id as it's unique across all tenants.

2023-11-07 09:35 UTC, tchiotludo approved these changes

2023-11-07 10:50 UTC, merged