Feat/taskitem progress
kestra-io/kestra pull request #2433
Opened 2023-11-03 10:48 UTC by loicmathieu

WIP PR to gather feedback

2023-11-08 10:57 UTC, loicmathieu commented
A screenshot from the new UI part:

![image](https://github.com/kestra-io/kestra/assets/1819009/055c8696-5030-46cd-99ef-f5be3ccba861)

2023-11-08 12:27 UTC, anna-geller requested changes
great work! One thing we need to improve is that we should expand this view by default in the same way as other `ForEach` tasks expand dynamic tasks by default

![image](https://github.com/kestra-io/kestra/assets/86264395/0f489b9d-1b79-4959-8418-2897ef8a335b)

2023-11-08 13:56 UTC, Skraye commented
close #2135

2023-11-10 08:24 UTC, tchiotludo requested changes

2023-11-10 08:24 UTC, tchiotludo commented on core/src/main/java/io/kestra/core/tasks/flows/Flow.java
> +public class Flow extends Task implements ExecutableTask<Flow.Output> {
The documentation is still not generated

2023-11-10 08:24 UTC, tchiotludo commented on core/src/main/java/io/kestra/core/tasks/flows/ForEachItem.java
> +        private final Map<String, Integer> iterations;
THe output is useless like this, please use strong typing: 
```java 
private Map<State.Type, Integer> states
private Integer max
...
```

2023-11-10 15:54 UTC, merged