fix/hide-unwanted-things-vs-code
kestra-io/kestra pull request #2554
Opened 2023-11-16 19:31 UTC by brian-mulier-p

closes #2336
closes #2338
closes #2339

2023-11-16 19:38 UTC, Skraye requested changes

2023-11-16 19:38 UTC, Skraye commented on ui/public/init.js
> +        contents: "{\"globalState\":\"{\\\"storage\\\":{" +
Put it in a file for more readability

2023-11-16 19:51 UTC, brian-mulier-p commented on ui/public/init.js
> +        contents: "{\"globalState\":\"{\\\"storage\\\":{" +
I moved them to a variable

2023-11-21 10:53 UTC, Skraye approved these changes
LGTM

2023-11-21 12:31 UTC, merged