feat(ui):add outputs and metrics based on value and name columns
kestra-io/kestra pull request #2560
Opened 2023-11-20 07:27 UTC by EdwardLi-coder

feat(ui): #2067

2023-11-22 07:19 UTC, EdwardLi-coder commented
Hello @Skraye, I've updated the backend code and have only added the condition to search by name in the metrics. However, I'm struggling to figure out how to implement the tags condition. If you have any suggestions or ideas, please let me know. Thank you.

2023-11-24 20:10 UTC, tchiotludo requested changes

2023-11-24 20:10 UTC, tchiotludo commented on ui/src/components/executions/MetricsTable.vue
> -    import Kicon from "../Kicon.vue";
Please remove the unexpected reindent

2023-11-24 21:36 UTC, EdwardLi-coder commented on ui/src/components/executions/MetricsTable.vue
> -    import Kicon from "../Kicon.vue";
> Please remove the unexpected reindent

Ok.I will remove the reindent

2024-02-21 13:59 UTC, closed without merging