fix(): prerender variables
kestra-io/kestra pull request #2588
Opened 2023-11-23 14:18 UTC by Skraye

2023-11-23 14:28 UTC, loicmathieu requested changes
I didn't see any test with a recursive rendering, please create one, we may want to throw is a loop is detected instead of doing a bad rendering.

Also, it appears you change the default behaviour and allow to use the old behavior but there is not usage of the old so it seems complicated for nothing.

2023-11-23 14:28 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/runners/RunContext.java
> +        return variableRenderer.render(inline, this.variables, true);
`true` is the default so you can revert this change

2023-11-23 14:28 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/runners/RunContext.java
> +    public String render(String inline, boolean renderVariables) throws IllegalVariableEvaluationException {
```suggestion
    public String render(String inline, boolean preprocessVariables) throws IllegalVariableEvaluationException {
```

I think it's better to call it preprocessed as it's what you do and variable are rendered anyway as we are recursive.

2023-11-23 14:28 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/runners/RunContext.java
> +        return variableRenderer.render(inline, mergeVariables(variables), true);
Revert as it's the default behaviour

2023-11-23 14:28 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/runners/RunContext.java
I think all changes inside the RunContext can be reverted as the new functions are not used anywhere.
Just keep it simple for now

2023-11-23 14:28 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/runners/VariableRenderer.java
> +    public String recursiveRender(String inline, Map<String, Object> variables, Boolean renderVariables) throws IllegalVariableEvaluationException {
```suggestion
    public String recursiveRender(String inline, Map<String, Object> variables, Boolean preprocessVariables) throws IllegalVariableEvaluationException {
```

2023-11-23 14:47 UTC, brian-mulier-p requested changes

2023-11-23 14:47 UTC, brian-mulier-p commented on core/src/test/java/io/kestra/core/runners/RunContextTest.java
> +        assertThat((String) execution.getTaskRunList().get(3).getOutputs().get("value"), containsString("toto"));
Please add an infinite loop test and assert that you get the result that preceeds the infinite loop turn
(var1: {{var2}}, var2: {{var3}}, var3: {{var1}})
=> render({{var1 | replace({'3': '4'})}}) => {{var4}}

2023-11-23 14:47 UTC, brian-mulier-p commented on core/src/test/java/io/kestra/core/runners/RunContextTest.java
> +        assertThat((String) execution.getTaskRunList().get(3).getOutputs().get("value"), containsString("toto"));
you can change the test as it's purely logic and not easily understandable but you get it

2023-11-23 14:50 UTC, Skraye commented
The `variables()` test has been updated

You can see that the task added to the flow depends on a vars, and the vars.period itself need to be rendered first, how the value return by the task would not contains any "toto"

```yaml
- id: variables
  type: io.kestra.core.tasks.debugs.Return
  format: "{{ vars.period | replace({':': 'toto'}) }}"
```

2023-11-23 15:36 UTC, loicmathieu requested changes
I really think it is a bad idea to store all intermediate rendering in a list to detect infinite loop.
It could blow away the memory if a big string is rendered (and we now it is).

If it's still doable today to create an infinite loop, remove your infinite loop handling code and proceed with the PR and open an issue. If not, we should hold this one.

2023-11-23 16:19 UTC, Skraye commented
@loicmathieu issue for the infinite loop : https://github.com/kestra-io/kestra/issues/2592
Pls approve if you consider the actual state is ok for variable rendering before rendering dynamic props

2023-11-23 16:34 UTC, loicmathieu approved these changes
I did't had time to QA it, @brian-mulier-p did you QA it?

2023-11-23 17:23 UTC, yuri1969 commented
FYI this PR also fixes #2466

2023-11-27 16:11 UTC, anna-geller approved these changes
QA pass

2023-11-28 16:24 UTC, merged