Feat/deserialization error
kestra-io/kestra pull request #2622
Opened 2023-11-30 15:42 UTC by loicmathieu

2023-12-05 14:03 UTC, loicmathieu commented
This PR is in draft because it needs https://github.com/kestra-io/kestra/pull/2601 to be merged before.

2023-12-06 11:02 UTC, brian-mulier-p requested changes
small changes

2023-12-06 11:02 UTC, brian-mulier-p commented on core/src/test/java/io/kestra/core/runners/DeserializationIssuesCaseTest.java
> +            () -> flows.get() != null && flows.get().stream().anyMatch(newFlow -> newFlow.uid().equals("company.team_hello-world_2")),
I guess it should also assert that tasks are empty ? :thinking:

2023-12-06 11:02 UTC, brian-mulier-p commented on jdbc/src/main/java/io/kestra/jdbc/JdbcWorkerTriggerResultQueueService.java
> +                        // silently ignore the message if we cannot do anything about it
log

2023-12-06 11:02 UTC, brian-mulier-p commented on jdbc/src/main/java/io/kestra/jdbc/runner/JdbcExecutor.java
> +                        // if we cannot create a FlowWithException, silently ignore the message
log

2023-12-12 09:32 UTC, brian-mulier-p approved these changes
LGTM :+1:

2023-12-18 08:12 UTC, merged