feat(core): add Pebble encrypt and decrypt functions
kestra-io/kestra pull request #2892
Opened 2024-01-19 09:30 UTC by loicmathieu

Fixes #2143

It can be QA with the following flow:

```yaml
id: cypher
namespace: company.team
tasks:
  - id: encrypt
    type: io.kestra.core.tasks.debugs.Return
    format: "{{encrypt('toto')}}"
  - id: logEncrypted
    type: io.kestra.core.tasks.log.Log
    message: "{{outputs.encrypt.value}}"
  - id: descrypt
    type: io.kestra.core.tasks.debugs.Return
    format: "{{decrypt(outputs.encrypt.value)}}"
  - id: logDecrypted
    type: io.kestra.core.tasks.log.Log
    message: "{{outputs.descrypt.value}}"
```

It didn't configure a key by default as it is a security risk if a user didn't change it, a message will pop up in case the user didn't specify one and the flow will be in error: `You must configure a base64 encoded AES 256 bit secret key in the 'kestra.crypto.secret-key' configuration property to be able to use encryption and decryption facilities`

For testing, you can generate a key [here](https://acte.ltd/utils/randomkeygen) and use a key of type 'Encryption key 256'.

2024-01-29 10:44 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/crypto/CryptoService.java
> +        cipher.init(Cipher.ENCRYPT_MODE, key, ivParameter);
It's fixed, I have no idea why the Sonar action didn't close this comment as 'Fixed'.

2024-01-31 01:24 UTC, anna-geller commented
to cross-check -- does the `encrypt` function/interface work in a way that it will be easy to use in various plugins like AWS and GCP that return a sensitive token? the encrypt functionality will be mostly used internally by plugins e.g., `aws.ecr.GetAuthToken` by default encodes the token, and only a downstream task that wants to consume it would need to use the `decrypt` function. This means that the `encrypt` will be mostly used internally by various plugins:

```yaml
id: python_aws_ecr
namespace: blueprint

tasks:
  - id: ecr
    type: io.kestra.plugin.aws.ecr.GetAuthToken
    accessKeyId: "{{ secret('AWS_ACCESS_KEY_ID') }}"
    secretKeyId: "{{ secret('AWS_SECRET_ACCESS_KEY') }}"
    region: eu-central-1

  - id: py
    type: io.kestra.plugin.scripts.python.Commands
    docker:
      image: 338306982838.dkr.ecr.eu-central-1.amazonaws.com/data-infastructure:latest
      credentials:
        username: AWS
        password: "{{ decrypt(outputs.ecr.token) }}"
    commands:
      - python --version # e.g. python yourscript.py
 ```

2024-01-31 08:06 UTC, loicmathieu commented
@anna-geller, for the moment, this is a couple of functions that must be used manually.

But behind those functions, there is a CryptoService that could be used by any tasks, if we want to do it often, we may want to think of how to offer this facility in an easy way.

2024-01-31 09:32 UTC, anna-geller commented
The AWS ECR and GCP auth token tasks linked on the GitHub issue are the main tasks that need to use it. Can you change the output on those tasks to be encrypted? To make it a non breaking behavior, perhaps we can encrypt the output of those tasks only if the encryption key you mentioned is set in kestra configuration?

2024-01-31 10:11 UTC, fhussonnois requested changes

2024-01-31 10:44 UTC, loicmathieu commented
@anna-geller your comment seems unrelated to the original issue which is to provide Pebble function to encode/decode sensitive data. Either the original issue is not correctly described and we should rework it and update this PR, either it's unrelated and a new issue should describe the adaptation needed to the tasks you listed.

2024-01-31 11:17 UTC, anna-geller commented
Sorry if the issue wasn't clear enough. The problem to be solved is that we don't want to have sensitive output stored in plain text. The pebble function might be just one possible solution

Send me a Google Meet or ping me via Slack huddle if it helps to discuss but the pebble alone won't solve the issue, the outputs on those two tasks I mentioned need to be adjusted

2024-01-31 11:25 UTC, anna-geller commented
@loicmathieu as requested, I adjusted the original issue to make it clearer what's the expected outcome and what the acceptance criteria

2024-01-31 11:47 UTC, loicmathieu commented
@anna-geller I remove the automatic fix so this PR will not fix the original issue.
What I don't fully understand is if we need those functions, or not. Please tell me if you think this is a good addition and should be merged or not.

2024-01-31 14:49 UTC, merged