WIP refactor(core): migrate to standard Java ServiceLoader for plugins
kestra-io/kestra pull request #3562
Opened 2024-04-15 21:54 UTC by fhussonnois

Changes:
- add new top level interface `Plugin`
- add new `JsonDeserializer` aware of the `PluginRegistry`
- add google AutoService for generating services files
- migrate to hibernate-validator for the JSR-303 (no bean introspection dependencies)
- update all Validation annotations to be complitant with the JSR-303
- remove all KestraApplicationContext stuffs
- fix some tests

part-of: kestra-io/plugin-template-test#25

2024-04-15 22:03 UTC, fhussonnois commented
**Test**
*  `io.kestra.core.docs.JsonSchemaGeneratorTest` FAILED --> need to be fixed or updated

**Issues**
* Issue on the `Pause` due to the `@NotEmpty` constraint on the inherited class `Sequential`
**Limitations**
* Micronaut `@Controller` are not anymore considered as plugins

2024-04-24 09:27 UTC, loicmathieu requested changes
Overall LGTM, but there is still some small things that I think should be improved:

- I'm not sure the PluginRegistry needs an interface.
- Can you explain the changes to validation, as it's a breaking change that would impact existing plugins
- Can you explain the Gradle change with the micronaut scope
- I have the feeling that the core vs external plugins can be simplified if not removed, this could be done later

I'll try this PR soon, one last thing that is missing is performance comparison. Starting Kestra when there is a lot of plugin takes some time, it would be interested to check if this PR improve or not this area.

2024-04-24 09:27 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/models/conditions/types/ExecutionFlowCondition.java
> +@JsonDeserialize
Is it still needed as not all conditions have it?

2024-04-24 09:27 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/docs/Plugin.java
> +            .filter(c -> !c.startsWith("org.kestra."))
What is it for? Is it already existing somewhere else?

2024-04-24 09:27 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/plugins/PluginScanner.java
> +                return;
Please keep this so we can remove class incorrectly detected as plugins

2024-04-24 09:27 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/tasks/flows/Sequential.java
> +    // FIXME -> issue with Pause @NotEmpty
I don't understand, this is overriden in the Pause task so it should work?

2024-04-24 09:27 UTC, loicmathieu commented on core/src/test/java/io/kestra/core/docs/JsonSchemaGeneratorTest.java
> +    @JsonDeserialize
Should not be needed

2024-04-24 09:27 UTC, loicmathieu commented on model/src/main/java/io/kestra/core/plugins/PluginRegistry.java
> +public interface PluginRegistry {
I don't think it should be in the model library

2024-04-24 09:27 UTC, loicmathieu commented on model/src/main/java/io/kestra/core/plugins/serdes/PluginDeserializer.java
> +public final class PluginDeserializer<T extends Plugin> extends JsonDeserializer<T> {
I don't think it should be in the model library

2024-04-24 09:27 UTC, loicmathieu commented on model/src/main/java/io/kestra/core/plugins/serdes/PluginDeserializer.java
> +            log.debug("Looking for Plugin for: {}",
```suggestion
            log.trace("Looking for Plugin for: {}",
```

2024-04-24 09:27 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/validations/CronExpression.java
> +    Class<? extends Payload>[] payload() default {};
Can you explain what's the purpose of this?

2024-04-24 09:28 UTC, loicmathieu commented
One last thing, split packages must be avoided if possible, so when moving stuff on the model library we should move all the classes of the package in it if possible.

2024-04-24 14:15 UTC, merged