Added REST methods for task and trigger validation that accept JSON body
kestra-io/kestra pull request #3785
Opened 2024-05-21 10:46 UTC by rybandrei2014

### What changes are being made and why?
Kestra doesn't provide rest endpoints for validation of task and triggers in JSON format. Endpoint for task/trigger validation /validate/task accepts only YAML body.
Following PR adds two new endpoints:
- /validate/task - endpoint for task validation, accepts JSON body
- /validate/trigger - endpoint for trigger validation, accepts JSON body

2024-07-11 11:52 UTC, loicmathieu commented
Hi @rybandrei2014 ,

Sorry for the late answer, can you also provide unit tests in https://github.com/kestra-io/kestra/blob/develop/webserver/src/test/java/io/kestra/webserver/controllers/api/FlowControllerTest.java

2024-07-16 15:21 UTC, rybandrei2014 commented
Hi @loicmathieu,

no worries, thanks for your reaction.

I added unit tests for new endpoints.

Thank you

2024-07-16 15:32 UTC, loicmathieu requested changes
Can you move all your tests data inline in the Java test class so they are more easily found and didn't add too many files.

You can use text blocks to deal with double quotes, for ex:
```java
String task = """
    {
      "id": "task_one",
      "type": "io.kestra.plugin.core.log.Log"
    }
"""
```

2024-07-16 15:32 UTC, loicmathieu commented on webserver/src/main/java/io/kestra/webserver/controllers/api/FlowController.java
> +    @ExecuteOn(TaskExecutors.IO)
```suggestion
    // This endpoint is not used by the Kestra UI nor our CLI but is provided for the API users for convenience
    @ExecuteOn(TaskExecutors.IO)
```

Adding a comment will prevent someone removing the method as not used ;)

2024-07-16 15:32 UTC, loicmathieu commented on webserver/src/main/java/io/kestra/webserver/controllers/api/FlowController.java
> +    @ExecuteOn(TaskExecutors.IO)
```suggestion
    // This endpoint is not used by the Kestra UI nor our CLI but is provided for the API users for convenience
    @ExecuteOn(TaskExecutors.IO)
```

2024-08-30 20:26 UTC, hhovhann commented on webserver/src/test/java/io/kestra/webserver/controllers/api/FlowControllerTest.java
> +        HttpResponse<List<ValidateConstraintViolation>> response = client.toBlocking().exchange(POST("/api/v1/flows/validate/task", task).contentType(MediaType.APPLICATION_JSON), Argument.listOf(Vali
Possible to define the `static final String VALIDATE_TASK_URL="/api/v1/flows/validate/task"` ?

2024-08-30 20:31 UTC, hhovhann commented on webserver/src/main/java/io/kestra/webserver/controllers/api/FlowController.java
> +            if (e.getCause() instanceof ConstraintViolationException constraintViolationException) {
Can `e.getCause()` be NULL ?
YES: 
```
if(e.getCause() != null && e.getCause() instanceof ConstraintViolationException constraintViolationException) {
}
```
NO: please ignore this comment

2024-09-02 10:04 UTC, loicmathieu commented
@rybandrei2014 ca you address my comments so we can proceed with the PR?

2024-09-25 13:15 UTC, loicmathieu approved these changes
LGTM, thanks

2024-09-25 13:39 UTC, rybandrei2014 commented
> @rybandrei2014 ca you address my comments so we can proceed with the PR?

Hello @loicmathieu, I am currently busy with my other project. Hopefully, I will be able to provide requested changes next week.

Sorry for keeping you waiting and late reply

2024-09-25 13:41 UTC, loicmathieu commented
@rybandrei2014 I made the necessary change and will now merge it.
Thanks again for your contribution.

2024-09-25 13:41 UTC, merged