fix(core): decrypt outputs for tasks within WorkingDirectory
kestra-io/kestra pull request #4001
Opened 2024-06-11 20:42 UTC by brian-mulier-p

closes #4000

2024-06-11 21:40 UTC, fhussonnois requested changes

2024-06-11 21:40 UTC, fhussonnois commented on core/src/main/java/io/kestra/core/runners/Worker.java
> +                    WorkerTaskResult workerTaskResult = this.run(currentWorkerTask.withRunContext(runContext.forWorkingDirectoryTask()), false);
I don't think you need to add the `@With` on the `WorkerTask`. Maybe you can just pass the runContext returned from the `forWorkingDirectoryTask` method directly when initializing the `currentWorkerTask` variable on line 287.

2024-06-11 21:40 UTC, fhussonnois commented on core/src/main/java/io/kestra/core/runners/RunContext.java
> +        Map<String, Object> decryptedVariables = new HashMap<>();
You can directly init the decryptedVariables map with  this.variables, and only update the `outputs` entry instead of iterating over all entries.

2024-06-12 07:40 UTC, brian-mulier-p commented on core/src/main/java/io/kestra/core/runners/Worker.java
> +                    WorkerTaskResult workerTaskResult = this.run(currentWorkerTask.withRunContext(runContext.forWorkingDirectoryTask()), false);
Oups didn't see that it was built right above my bad :+1:

2024-06-12 08:41 UTC, merged