WIP feat(core): add support for pebble filters/functions as plugin
kestra-io/kestra pull request #4645
Opened 2024-08-13 07:28 UTC by fhussonnois

This PR is a POC to allow users to define custom filters and functions for pebble as plugins:

**Examples:** 

A custom Pebble Filter :

```java
public class UppercaseFilter extends PebbleFilter {

    @Override
    public Object apply(Object input, Map<String, Object> args, PebbleTemplate self, EvaluationContext context, int lineNumber) throws PebbleException {
        return Optional.ofNullable(input)
            .map(Object::toString)
            .map(s -> s.toUpperCase(Locale.ROOT)).orElse(null);
    }

    @Override
    public List<String> getArgumentNames() {
        return List.of();
    }
}
```

A custom Pebble Function :

```java
public class UppercaseFunction extends PebbleFunction {

    @Override
    public Object execute(Map<String, Object> args, PebbleTemplate self, EvaluationContext context, int lineNumber) {
        if (!args.containsKey("value")) {
            throw new PebbleException(null, "The 'uppercase' function expects one arguments 'value'", lineNumber, self.getName());
        }
        String value = (String) args.get("value");
        return Optional.ofNullable(value).map(s -> s.toUpperCase(Locale.ROOT)).orElse(null);
    }

    @Override
    public List<String> getArgumentNames() {
        return List.of("value");
    }
}
```

**Limitation(s):**

Currently this PR does not provide embedded plugin doc for Pebble functions/filters (i.e., those plugin are not visible in the UI)

2024-08-13 07:45 UTC, brian-mulier-p commented on core/src/main/java/io/kestra/core/expression/PebbleFilter.java
> +            .replace(PebbleFilter.class.getSimpleName(), "");
If you trim "Filter" from the name you can't have "PebbleFilter" in the name afterwards :P

2024-08-13 07:45 UTC, brian-mulier-p commented on core/src/main/java/io/kestra/core/expression/PebbleFunction.java
> +            .replace(PebbleFunction.class.getSimpleName(), "");
Same as "Filter" trim

2024-08-16 15:15 UTC, anna-geller approved these changes
nice!

2024-09-02 10:11 UTC, loicmathieu requested changes

2024-09-02 10:11 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/plugins/RegisteredPlugin.java
> +            return TaskRunner.class;
Seems not OK

2024-09-02 10:11 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/expression/PebbleFilter.java
> +            .replace(PebbleFilter.class.getSimpleName(), "")
```suggestion
            .replace(this.getClass().getSimpleName(), "")
```

2024-09-02 10:11 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/expression/PebbleFunction.java
> +            .replace(PebbleFunction.class.getSimpleName(), "")
```suggestion
            .replace(this.getClass().getSimpleName(), "")
```

2024-09-02 14:40 UTC, closed without merging