Renaming RUNNING to IN-PROGRESS within the ForEachItem execution #3453
kestra-io/kestra pull request #5471
Opened 2024-10-15 11:30 UTC by iamviqar

### What changes are being made and why?

This closes #3453 
---

### How the changes have been QAed?

Validated on local setup, please refer the screenshot below 

![Screenshot from 2024-10-15 16-25-15](https://github.com/user-attachments/assets/8d48cff2-a42a-48cd-9e56-84d5fafb4829)

---

### Setup Instructions

2024-10-17 07:56 UTC, MilosPaunovic commented
@Skraye Could you check this one to make sure it won't break anything, as it is confusing me what are we trying to achieve here and the way to get there.

2024-10-17 08:08 UTC, Skraye requested changes
Good job! Even more than what we asked! 
Just some small changes and we're good to go :rocket:

2024-10-17 08:08 UTC, Skraye commented on ui/src/components/executions/ForEachStatus.vue
> +                    return State.INPROGRESS;
Please replace by only  `IN-PROGRESS`, not using the state

2024-10-17 08:08 UTC, Skraye commented on ui/src/utils/state.js
> +    },
We wont add this as a real state for now, so you can remove it

2024-10-17 08:08 UTC, Skraye commented on ui/src/utils/state.js
> +
Can also be removed

2024-10-17 18:59 UTC, iamviqar commented
@Skraye I've addressed your review comments, please re-review . Thanks

2024-10-18 07:08 UTC, Skraye approved these changes
LGTM! Nice contribution :medal_sports:

2024-10-18 07:09 UTC, merged