Navbar Auto-Switches to Line-by-Line Layout on Zoom for Improved Accessibility
kestra-io/kestra pull request #5506
Opened 2024-10-16 22:36 UTC by shawnfrost69

### What changes are being made and why?

The CSS for the .el-tabs__nav has been modified to allow navbar items to wrap onto new lines when the page is zoomed in. This change improves usability and accessibility by ensuring that all navbar items remain visible, even when zoomed to a larger size.
---

### How the changes have been QAed?
The modification was tested by zooming the page at various levels (150%, 200%) to confirm that the navbar adjusts dynamically, wrapping items to the next line as needed.

### Setup Instructions
No additional setup is required. Just apply the CSS rule below:

.el-tabs__nav {
          display: flex;
          flex-wrap: wrap;
}

Before:
![Screenshot 2024-10-17 at 3 57 48 AM](https://github.com/user-attachments/assets/a0816808-3930-4178-80d7-e4e4e59a5dc8)

After:
![Screenshot 2024-10-17 at 4 04 45 AM](https://github.com/user-attachments/assets/63739acd-fa92-41fa-903a-d36384129932)

2024-10-17 07:15 UTC, MilosPaunovic commented
Hi @shawnfrost69,

Unfortunately, this PR does not solve the initial issue.

The problem was that when you have flow revision (when you have saved multiple versions of it) and show changes on a `side-by-side` editor, when you zoom in browser, editor automatically changes to `line-by-line`, by the select box remains to say that it is `side-by-side`.

Could you try and solve that issue?

2024-10-17 08:26 UTC, shawnfrost69 commented
Hi @MilosPaunovic Sorry for the discrepancy and Thanks for the information.
Could you please confirm the below point :

(A). when the user zooms in on the browser, the editor automatically changes to **line-by-line** so, according to that input field, it needs to show the line-by-line option instead of side by side.

(B). And there is no need to change the size of the Navbar.

2024-10-17 08:27 UTC, MilosPaunovic commented
Yup, that is now the correct expectation.

2024-10-17 08:35 UTC, shawnfrost69 commented
Thanks, @MilosPaunovic I'll work on this issue.

2024-10-17 09:30 UTC, shawnfrost69 commented
Hi, @MilosPaunovic How can I approach this issue? 
![image](https://github.com/user-attachments/assets/8b87d4bf-12a3-42d0-897b-634e0591aa3d)

(A). I had to try to remove the package-lock.json file and node_modules folder and did a fresh npm I inside the UI folder, but still it is not working.

(B). whenever I do the npm start I get my localhost up but once I browse the URL it shows me the same error again.
![image](https://github.com/user-attachments/assets/ee39c002-bb4d-4a3b-babe-9815fc9842d7)

(C). I also pulled the latest changes but still the same issue.

2024-10-17 09:34 UTC, MilosPaunovic commented
Maybe this would be something @brian-mulier-p has some idea about?

2024-10-20 15:23 UTC, shawnfrost69 commented
Hi @MilosPaunovic  I have updated the pull request, Could you please take a moment to review it? I believe this should address the issue. Thanks..

2024-10-22 09:16 UTC, shawnfrost69 commented
@MilosPaunovic  is there any issue in these changes ? can we ask for review and merge?

2024-10-22 09:57 UTC, MilosPaunovic commented
Hi @shawnfrost69,

This is not ideal approach.

We should detect the view change event of the Monaco Editor, and update the select field accordingly. With your solution we are relying on pixel ratio which could be very flaky, as there are multiple browsers with astonishingly high number of resolutions and this probably won't work on all of them.

Can you try to explore a bit around `monaco-editor` APIs and check if we somehow can detect the change in `diffEditor` view mode?

2024-10-22 10:00 UTC, shawnfrost69 commented
Sure

2024-11-04 08:52 UTC, MilosPaunovic requested changes
Hi @shawnfrost69, is there any progress on this or are you giving up on this particular issue?

2024-11-04 12:31 UTC, shawnfrost69 commented
Hi @MilosPaunovic, I've tried many approaches, but nothing is working smoothly with the Monaco Editor except this one. In the meantime, you can unassign this. If I find a solution, I'll come back and update you here. Thanks!

2024-11-04 12:33 UTC, MilosPaunovic commented
Okay, if that's the case, I'll close this PR for now. We can re-open if necessary.

2024-11-04 12:33 UTC, closed without merging