feat(ui) Reworked the Trigger page to show only columns that have data
kestra-io/kestra pull request #5555
Opened 2024-10-19 20:56 UTC by MRADUL9936

### What changes are being made and why?

 made changes in ui/src/components/admin/triggers.vue , because this is the parent component which is responsible for 
fetching the data from store and rendering the table .
I am using a method to filter out the columns which is having no data , and rendering these columns.

![Screenshot (253)](https://github.com/user-attachments/assets/b62e3a9d-25cd-44fe-bb58-cc45830c4c1a)

### How the changes have been QAed?

  Tested in Different Browsers 

closes #5546

2024-10-21 06:30 UTC, MilosPaunovic requested changes
Le't try to keep the formatting changes to a minimum, as it will be easier to review PR.

2024-10-21 06:30 UTC, MilosPaunovic commented on ui/src/components/admin/Triggers.vue
> -                        <el-table-column
Where did this column go missing?

2024-10-21 06:30 UTC, MilosPaunovic commented on ui/src/components/admin/Triggers.vue
> -                        <el-table-column column-key="disable" class-name="row-action">
Also, this column seem missing too.

2024-10-21 07:00 UTC, Skraye commented
@MRADUL9936 Note that Anna do not ask to remove the column, only to hide them if they are empty, however they are still very important

2024-10-23 22:25 UTC, MRADUL9936 commented
@MilosPaunovic  I made changes , can u please review it now .

2024-10-24 11:40 UTC, MilosPaunovic approved these changes
LGTM! 🚀

2024-10-24 11:40 UTC, merged