Added | string
kestra-io/kestra pull request #5585
Opened 2024-10-21 19:36 UTC by RashmitTopG

### What changes are being made and why?

Added a new StringFilter to the Kestra project, which converts numeric inputs and string representations of numbers into their string form. This feature enhances template flexibility by allowing users to handle numeric values as strings easily.
This PR closes #5528 .

---

### How the changes have been QAed?

# Example flow code demonstrating the use of the string filter in a Pebble template
template: |

```yaml
  {{ 123 | string }}   # Expected output: "123"
  {{ "456.78" | string }}  # Expected output: "456.78"
  {{ "invalid" | string }}  # Expected to raise a PebbleException
```

# This example shows how the new StringFilter behaves with different input types.

---

2024-10-21 19:39 UTC, RashmitTopG commented
@anna-geller I've submitted a pull request adding a StringFilter to the Kestra project that converts numbers to strings. Please review and suggest improvements if any .

2024-10-28 10:06 UTC, RashmitTopG commented
@MilosPaunovic can you please review this PR !!

2024-10-28 10:20 UTC, MilosPaunovic commented
Nope, Java is not my strong suit. @Skraye will take a look when he gets the chance.

2024-10-29 05:55 UTC, shrutimantri commented on core/src/test/java/io/kestra/core/runners/pebble/filters/StringFilter.java
> +package io.kestra.core.runners.pebble.filters;
The file name should be `StringFilterTest.java`

2024-10-29 05:57 UTC, shrutimantri commented on core/src/test/java/io/kestra/core/runners/pebble/filters/StringFilter.java
> +
Should this be a test file given that it is in the test folder?
The contents look to be duplicate as present in the above file.

2024-10-29 07:56 UTC, Skraye requested changes

2024-10-29 07:56 UTC, Skraye commented on core/src/main/java/io/kestra/core/runners/pebble/Extension.java
> +        operators.add(
Noise, remove it

2024-10-29 07:56 UTC, Skraye commented on core/src/test/java/io/kestra/core/runners/pebble/filters/StringFilter.java
> +public class StringFilter implements Filter {
As Shruti said, this is a duplicate of the class, please remove this file and implement a proper test

2024-10-29 07:56 UTC, Skraye commented on core/src/main/java/io/kestra/core/runners/pebble/filters/StringFilter.java
> +                lineNumber, self.getName());
The idea is good, but you focused too much on numbers : 
- When the filter is applied on a String, it should not fail, it just does nothing
-  The filter string could be applied to anything, as every Java object has the method `.toString()`

Line 35 you're taking a String input, you cast int to a number to then cast it to String, it does not make sense

2024-11-12 07:54 UTC, Skraye commented
@RashmitTopG Any update on this?

2024-12-03 09:32 UTC, MilosPaunovic commented
Hi @RashmitTopG, are there any updates on this one?

2025-02-17 08:30 UTC, anna-geller commented
sorry @RashmitTopG, I have to close this one due to the lack of your responses to the PR review for over 3 months 😢

2025-02-17 08:30 UTC, closed without merging