Feature/2197 replay with input
kestra-io/kestra pull request #5698
Opened 2024-10-28 20:49 UTC by iamviqar

### What changes are being made and why?

---

### How the changes have been QAed?

---

### Setup Instructions

2024-10-29 08:23 UTC, Skraye requested changes
* Change property name in component
* Do not create new endpoint
* As you're modifying controllers, do not forget to add new tests

More details in the review comments

2024-10-29 08:23 UTC, Skraye commented on ui/src/components/executions/Overview.vue
> +                <restart is-replay :initial-inputs="flow" :execution="execution" class="ms-0" @follow="forwardEvent('follow', $event)" />
```suggestion
                <restart is-replay :flow="flow" :execution="execution" class="ms-0" @follow="forwardEvent('follow', $event)" />
```

If you're passing a flow, just call it flow, same for replay component

2024-10-29 08:23 UTC, Skraye commented on ui/src/stores/executions.js
> +                `${apiUrl(this)}/executions/${options.executionId}/restart-with-input`,
Do not modify the path

2024-10-29 08:23 UTC, Skraye commented on webserver/src/main/java/io/kestra/webserver/controllers/api/ExecutionController.java
> +    @Post(uri = "/{executionId}/restart-with-input")
Those endpoint (duplicated of the original one for now) are not necessary, just need to enhance the existing one

same apply for the replay endpoint

2024-10-29 08:34 UTC, iamviqar commented
Thanks, @Skraye , for your review comments! I’ll address them as soon as possible.

2024-10-30 06:57 UTC, iamviqar commented
@Skraye I've addressed most of your code review comments, except for the tests on the backend API. I marked this PR as a draft because there are still pending implementations for the backend API. I'm currently trying to determine how to pass the input values received as parameters in the execution controller to the actual execution. I noticed there aren't any setter methods for inputs in the execution object, and I would appreciate your assistance with this.

Regards
tagging @MilosPaunovic

2024-11-12 07:58 UTC, Skraye commented
Hello @iamviqar, any update on this?

2024-12-03 09:36 UTC, MilosPaunovic commented
Hi @iamviqar, are there any updates on this?

2025-02-19 02:04 UTC, anna-geller commented
@MilosPaunovic @Skraye can one of you take over to finish and merge the PR?

2025-02-19 07:12 UTC, MilosPaunovic commented
This would have to be @Skraye, as it would involve some Java work also.

2025-09-02 11:10 UTC, Piyush-r-bhaskar commented
Closing in favour of https://github.com/kestra-io/kestra/pull/11010

2025-09-02 11:10 UTC, closed without merging