fileURI() Pebble Function
kestra-io/kestra pull request #5888
Opened 2024-11-13 06:35 UTC by asharan2buff

### What changes are being made and why?

--- Crated a fileURI() to retrieve namespace from path.

### How the changes have been QAed?

---

### Setup Instructions

2024-11-13 08:12 UTC, loicmathieu requested changes
It also needs a test

2024-11-13 08:12 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/runners/pebble/functions/GetFileURI.java
> +    private static final String ERROR_MESSAGE = "The 'getFileURI' function expects an argument 'path' that is a path to a namespace file or an internal storage URI.";
```suggestion
    private static final String ERROR_MESSAGE = "The 'getFileURI' function expects an argument 'path' that is a path to a namespace file.";
```

2024-11-13 08:12 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/runners/pebble/functions/GetFileURI.java
> +        return List.of("flow");
```suggestion
        return List.of("path");
```

2024-11-14 19:19 UTC, asharan2buff commented
@loicmathieu I am unable to get the value of "flow" variable from context. I see a similar implementation in other functions. Am I missing anything?

2024-11-15 14:46 UTC, loicmathieu commented
@asharan2buff it's because in test you will have a mocked run context with no variables in it.
We usually init variables manually and pass them to the render function as an extra parameter:

```java
Map<String, Object> variables = Map.of(
            "flow", Map.of(
                "id", "myFlow",
                "namespace", "myNamespace)
        );
variableRenderer.render("[...]", variables);
```

2024-11-20 07:04 UTC, asharan2buff commented
@loicmathieu Added the test case. Please proceed with the review.

2024-11-20 08:57 UTC, loicmathieu approved these changes
LGTM, thanks

2024-11-20 09:14 UTC, merged

2024-11-20 19:16 UTC, MilosPaunovic commented
Just a small note for the future @asharan2buff, if you could use **GitHub Keywords** when opening PRs to connect it to the proper issue (to automate the entire process a bit more), it would be super helpful to us. You can read a bit more about it [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue) (I've added closing keyword for this particular issue).

Thanks for this contribution! 🚀