Fix(Webserver) #6225 Added check in file creation path for _flows*
kestra-io/kestra pull request #6228
Opened 2024-12-02 08:47 UTC by coderkill

### What changes are being made and why?

Kestra allows the creation of files and directories with names starting with _flows*, despite the system's default restrictions intended to prevent such creations. Additionally, it fails to block the creation of folders starting with _flows*. 
---

### How the changes have been QAed?

I manually tested these examples:
Failed Test cases:
![image](https://github.com/user-attachments/assets/b1503260-29ef-4c5c-ba7a-0f52bcd251b3)
![image](https://github.com/user-attachments/assets/feff7c5c-a41a-4a1a-8d76-a544dee99707)
![image](https://github.com/user-attachments/assets/2ffbf17a-45d3-4cf3-be18-4aa1bf7ce19c)

Subfolder _flows* check:
![image](https://github.com/user-attachments/assets/0d3b3d35-f114-4ad9-b592-754146779d31)

PositiveTest case
![image](https://github.com/user-attachments/assets/0f942bf5-ee93-452f-a709-65bacc2ab547)

Note that this is not a replacement for unit tests but rather a way to demonstrate how the changes work in a real-life scenario, as the end-user would experience them.

2024-12-03 10:01 UTC, loicmathieu commented
Hi,
Thanks for doing this.
I wonder if it would makes sense to only prevent files starting with `_flows` inside of containing. @brian-mulier-p WDYT?

It needs a test inside the existing NamespaceFileController test.

I also wonder if we should not do the same check in the UI to warn the user before he try to save the file. This is best practice, we usually duplicate this kind of checks in the UI and in the backend.

2024-12-03 12:12 UTC, coderkill commented
> Hi, Thanks for doing this. I wonder if it would makes sense to only prevent files starting with `_flows` inside of containing. @brian-mulier-p WDYT?
> 
> It needs a test inside the existing NamespaceFileController test.
> 
> I also wonder if we should not do the same check in the UI to warn the user before he try to save the file. This is best practice, we usually duplicate this kind of checks in the UI and in the backend.

Hi,

I would be happy to write the test case but I am not able to run them on my local so hence wasnt able to do it:

I am getting the following error when running on local inside Intellij:

Bean definition [io.kestra.webserver.services.BasicAuthService] could not be loaded: Failed to inject value for parameter [dslContext] of class: io.kestra.jdbc.JooqDSLContextWrapper

Message: Multiple possible bean candidates found: [DSLContext, DSLContext]
Path Taken: new BasicAuthService() --> BasicAuthService.settingRepository --> new H2SettingRepository([H2Repository<Setting T> repository],ApplicationContext applicationContext) --> new H2Repository(JdbcTableConfig jdbcTableConfig,QueueService queueService,[JooqDSLContextWrapper dslContextWrapper]) --> new JooqDSLContextWrapper([DSLContext dslContext],RetryUtils retryUtils)
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [io.kestra.webserver.services.BasicAuthService] could not be loaded: Failed to inject value for parameter [dslContext] of class: io.kestra.jdbc.JooqDSLContextWrapper

Message: Multiple possible bean candidates found: [DSLContext, DSLContext]
Path Taken: new BasicAuthService() --> BasicAuthService.settingRepository --> new H2SettingRepository([H2Repository<Setting T> repository],ApplicationContext applicationContext) --> new H2Repository(JdbcTableConfig jdbcTableConfig,QueueService queueService,[JooqDSLContextWrapper dslContextWrapper]) --> new JooqDSLContextWrapper([DSLContext dslContext],RetryUtils retryUtils)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:2000)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:314)
	at io.micronaut.context.DefaultBeanContext.configureAndStartContext(DefaultBeanContext.java:3318)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:345)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:216)
	at io.micronaut.test.extensions.AbstractMicronautExtension.startApplicationContext(AbstractMicronautExtension.java:507)
	at io.micronaut.test.extensions.AbstractMicronautExtension.beforeClass(AbstractMicronautExtension.java:346)
	at io.micronaut.test.extensions.junit5.MicronautJunit5Extension.beforeAll(MicronautJunit5Extension.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [dslContext] of class: io.kestra.jdbc.JooqDSLContextWrapper

Is there something I am doing wrong?

2024-12-03 12:54 UTC, loicmathieu commented
No, I'm not sure why you have this issue, you can start a discussion on our Slack on the contributors channels so we can help troubleshoot this test run issue.

2024-12-04 08:35 UTC, coderkill commented
I have tried posting the error on slack but to no avail, I have written the test cases but I am not able to run it due to the above error. It seems to be happening for all controller test classes.

2024-12-04 11:46 UTC, coderkill commented
I have pushed my test case as requested

2024-12-04 13:29 UTC, loicmathieu reviewed
LGTM however I want to discuss if we should not switch to startWith and duplicate the check in the UI internally before merging it.

2024-12-04 14:11 UTC, brian-mulier-p commented
Hello ! Makes sense to use startsWith, just mind about the leading "/" of namespace files :)

2024-12-05 08:21 UTC, coderkill commented
I have done some analysis, The difference in using startsWith from regex is that you will be able to create subfolders with the keyword _flows using startsWith. eg: /abc/_flows is a valid path. The same applies to files. eg /abc/_flows.txt is a valid file. The previous regex logic would stop it. I have made the changes on my local and tested them out. would you like for me to go forward and push them

2024-12-05 10:33 UTC, coderkill commented
Proof of fix:

![image](https://github.com/user-attachments/assets/42001dff-5ff7-4685-b260-0defbcb73ee2)
![image](https://github.com/user-attachments/assets/584544cf-a61c-462d-8168-69178aa83b9d)
![image](https://github.com/user-attachments/assets/57fdc0e2-4439-4b0d-8a6b-3bdeb72a87ae)
![image](https://github.com/user-attachments/assets/a82adfdc-fa11-4ab9-88f5-945197a521aa)

2024-12-05 12:30 UTC, coderkill commented
The Junit tests have passed, something else has caused the build to fail

2024-12-08 07:26 UTC, coderkill commented
Hi,

Any update on this?

2024-12-09 10:32 UTC, brian-mulier-p requested changes
Please do the following changes and we're good

2024-12-09 10:32 UTC, brian-mulier-p commented on webserver/src/main/java/io/kestra/webserver/controllers/api/NamespaceFileController.java
> +        if (filePaths.length != 0 && filePaths[0].startsWith(FLOWS_FOLDER)) {
```suggestion
        if (filePaths.length != 0 && filePaths[0].equals(FLOWS_FOLDER)) {
```
the startsWith was only if we compared the full path but here we should only do the import flow behaviour if the path part is actually the entire flow folder name

2024-12-09 10:32 UTC, brian-mulier-p commented on webserver/src/main/java/io/kestra/webserver/controllers/api/NamespaceFileController.java
>                  throw new IllegalArgumentException("Invalid flow file path: " + filePath);
```suggestion
                throw new IllegalArgumentException("Invalid flow file path: " + filePath + ". To import a flow, the file path should follow this template: /" + FLOWS_FOLDER + "/{flowId}.yml");
```

2024-12-09 10:32 UTC, brian-mulier-p commented on webserver/src/main/java/io/kestra/webserver/controllers/api/NamespaceFileController.java
>                  throw new IllegalArgumentException("Invalid flow file path: " + filePath);
If it breaks some tests please fix them

2024-12-09 10:32 UTC, brian-mulier-p commented on webserver/src/main/java/io/kestra/webserver/controllers/api/NamespaceFileController.java
> +        if (splitPath[0].startsWith(FLOWS_FOLDER)) {
```suggestion
        if (splitPath[0].equals(FLOWS_FOLDER)) {
```

2024-12-09 10:32 UTC, brian-mulier-p commented on webserver/src/test/java/io/kestra/webserver/controllers/api/NamespaceFileControllerTest.java
> +                        "/api/v1/namespaces/" + NAMESPACE + "/files/directory?path=/_flows2",
To me this should be ok... No need to reserve the entire _flows{...} folders, we just need one exclusive

2024-12-09 10:32 UTC, brian-mulier-p commented on webserver/src/test/java/io/kestra/webserver/controllers/api/NamespaceFileControllerTest.java
> +                .contentType(MediaType.MULTIPART_FORM_DATA_TYPE)
Same as above, should be allowed

2024-12-09 12:07 UTC, coderkill commented on webserver/src/test/java/io/kestra/webserver/controllers/api/NamespaceFileControllerTest.java
> +                        "/api/v1/namespaces/" + NAMESPACE + "/files/directory?path=/_flows2",
That means we want to allow _flows* from now on

2024-12-09 14:17 UTC, coderkill commented
@brian-mulier-p I have made the changes. Please review

2024-12-09 18:17 UTC, brian-mulier-p commented
After further looks I'm not sure we want to do that. The previous implementation allowed to provide multiple forbidden patterns which may be a desirable thing, now you're hardcoding every forbidden paths logic.

Looking at the original issue, I'm not sure it's a true issue, as said in comment we just want to reserve the `_flows` folder. Folders like `_flows{additional}` are ok imo. Why do you consider this worth a change?

2024-12-09 18:28 UTC, coderkill commented
The main issue was that it allowed the creation of **files** with name _**_flows**_ which is reserved. The previous logic (the regex logic) didn’t allow entry (can’t open) into _flows* directories which the user might have created. So I assumed that logic was intentional and built it on that. The main problem is creation of _flows file which is restricted.

2024-12-09 19:48 UTC, brian-mulier-p commented
Ideally, any _flows{somethingMore} directory is accessible, _flows is not.
For files yes _flows files should be forbidden so there may be a gap that must be filled :+1:

2024-12-10 01:51 UTC, coderkill commented
@brian-mulier-p I agree, the above logic is inline with what you have mentioned. It doesn’t allow the creation of file named _flows and it allows directories with name _flows*(including entering it). I will provide the screenshots as well after which we can confirm and merge.

2024-12-10 06:30 UTC, coderkill commented
![image](https://github.com/user-attachments/assets/453989b0-05ee-45ff-938d-eff37bd1bd90)
![image](https://github.com/user-attachments/assets/3f2e763d-bdb9-4229-ad6b-8084b399a338)
![image](https://github.com/user-attachments/assets/efcb4898-a43a-44ec-8c7e-b5a6ce988477)

Valid paths:
![Uploading image.png…]()

2024-12-10 06:30 UTC, coderkill commented
![image](https://github.com/user-attachments/assets/453989b0-05ee-45ff-938d-eff37bd1bd90)
![image](https://github.com/user-attachments/assets/3f2e763d-bdb9-4229-ad6b-8084b399a338)
![image](https://github.com/user-attachments/assets/efcb4898-a43a-44ec-8c7e-b5a6ce988477)

Valid paths:
![image](https://github.com/user-attachments/assets/ba3cbb6b-c267-4901-9b18-f41cb975562d)

2024-12-10 06:32 UTC, coderkill commented
![image](https://github.com/user-attachments/assets/f5202a95-7739-4bc3-862f-4f606a89c0bc)
![image](https://github.com/user-attachments/assets/43509da8-fd2a-4fc4-b312-6feea61796a2)
![image](https://github.com/user-attachments/assets/e9ed1d13-40cc-416c-b919-a06dc62b247e)


Valid scenarios:
![image](https://github.com/user-attachments/assets/dfeb52af-a2f6-465c-a58b-c145926e0390)

2024-12-10 06:34 UTC, coderkill commented
Do have a look at the above screenshots. I have outlined what the user sees when trying to create folders and files when using reserved keywords

2024-12-10 14:24 UTC, brian-mulier-p commented
It looks correct except we should remove the error message part where there is "To import flow..." because it only makes sense for the import process. My bad again I didn't see it was wider than just the import so it can just be rolled back.

Still as said it would be great to keep the regex pattern thing because it will allow to extend the forbidden paths later on

2024-12-10 14:33 UTC, coderkill commented
@brian-mulier-p I had previously kept the regex change which makes  _flows* as forbidden path. (That means no folder or file will be able created with that regex). Do you want me to revert my change?

2024-12-10 15:11 UTC, brian-mulier-p commented
Regex should be adapted to work for all the cases I described above

2024-12-10 15:12 UTC, brian-mulier-p commented
I suggest putting all the tests I said above and then put back the regex and adapt it so that it covers everything

2024-12-11 06:56 UTC, coderkill commented
@brian-mulier-p 

private final List<Pattern> forbiddenPathPatterns = List.of(
        Pattern.compile("/" + FLOWS_FOLDER + ".*")
    );
    
    This is the regex previously for forbidden path So I am a little confused as to what needs to be done. Can you please rehighlight what needs to be done so that I can work on it.

2024-12-11 12:33 UTC, brian-mulier-p commented
The putNamespaceFiles should be left unchanged imo.
For the forbiddenPathsGuard should be left unchanged also but the pattern could be updated to:
`Pattern.compile("/" + FLOWS_FOLDER + "(/.*)?$")`

2024-12-11 13:13 UTC, coderkill commented
I am assuming when you say "putNamespaceFiles should be left unchanged", do you mean of my latest changes?

When it comes to the forbiddenPathsGuard, My latest change will not allow opening of _flows directory. Which what your regex is doing, If you want me to use regex instead of startsWith then I can do that. but the behavior will be same as my latest code change.

2024-12-11 14:13 UTC, brian-mulier-p commented
As said we should keep the regex implementation as it's a list of patterns instead of an hardcoded single if, I like the ability to extend in a simple way which paths we want to forbid in the future.
For the "putNamespaceFiles should be left unchanged" I mean literally keep what was there before

2024-12-11 15:15 UTC, coderkill commented
> As said we should keep the regex implementation as it's a list of patterns instead of an hardcoded single if, I like the ability to extend in a simple way which paths we want to forbid in the future. For the "putNamespaceFiles should be left unchanged" I mean literally keep what was there before

If we keep putNameSpaceFiles() as before then we will be able to create the file _flows which is what we want to prevent.
![image](https://github.com/user-attachments/assets/a92df83d-78d9-4acc-a47c-165a35a2304c)

I understand the regex implementation for the forbiddenPathsGuard and will work on it.

2024-12-12 09:06 UTC, brian-mulier-p commented
> If we keep putNameSpaceFiles() as before then we will be able to create the file _flows which is what we want to prevent (if we keep it from the original code base, if you meant the changes I have done before please clarify).
You can just add something for that

2024-12-18 13:12 UTC, coderkill commented
Noted, making changes

2024-12-18 13:29 UTC, coderkill commented
Valid cases
![image](https://github.com/user-attachments/assets/80953b73-eaa9-4d25-a27a-27e5d0428ea3)

File creation
![image](https://github.com/user-attachments/assets/5f44188f-2a54-40f5-bae7-feb801454a36)

Folder creation
![image](https://github.com/user-attachments/assets/77dc131a-60af-4306-92ae-c229bddbd39c)

2024-12-22 07:01 UTC, coderkill commented
@brian-mulier-p Any update? Do you have any other suggestions?

2024-12-23 07:31 UTC, MilosPaunovic commented
Brian is going to be off for the next few weeks. @loicmathieu can do the review here, but first, you need to sort the conflict you're having in `webserver/src/test/java/io/kestra/webserver/controllers/api/NamespaceFileControllerTest.java` file.

2024-12-23 08:23 UTC, coderkill commented
> Brian is going to be off for the next few weeks. @loicmathieu can do the review here, but first, you need to sort the conflict you're having in `webserver/src/test/java/io/kestra/webserver/controllers/api/NamespaceFileControllerTest.java` file.

Done

2024-12-26 07:49 UTC, coderkill commented
@loicmathieu do have a look at the PR and let me know if anything else needs to be done

2024-12-30 06:35 UTC, coderkill commented
@MilosPaunovic Any update on the above?

2024-12-30 07:08 UTC, MilosPaunovic commented
It's holiday season here, so lot's of people are on a leave. Don't worry, when someone is available, this will be reviewed.

2024-12-30 11:55 UTC, loicmathieu commented
I prefer to wait for @brian-mulier-p as he's the one aware of the needed change.

2025-01-06 08:43 UTC, brian-mulier-p requested changes
Tiny change then we're good

2025-01-06 08:43 UTC, brian-mulier-p commented on webserver/src/main/java/io/kestra/webserver/controllers/api/NamespaceFileController.java
>          }
The leading slash is mandatory for this to work

2025-01-12 09:32 UTC, coderkill commented on webserver/src/main/java/io/kestra/webserver/controllers/api/NamespaceFileController.java
>          }
Done!

2025-01-16 06:20 UTC, coderkill commented
@brian-mulier-p Do have a look at the PR and let me know if its good now!

2025-01-16 10:17 UTC, brian-mulier-p approved these changes
LGTM

2025-01-16 11:06 UTC, merged