#6207 Added Random Number generator
kestra-io/kestra pull request #6267
Opened 2024-12-03 14:35 UTC by coderkill

### What changes are being made and why?

Python:

import random

random_value = random.randint(0, 1)

Added that as pebble function for Java

### How the changes have been QAed?

Written extensive Junits

2024-12-03 16:26 UTC, MilosPaunovic commented
Just a small note for the future, if you could use **GitHub Keywords** when opening PRs to connect it to the proper issue (to automate the entire process a bit more), it would be super helpful to us. You can read a bit more about it [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue) (I've added closing keyword for this particular issue).

2024-12-03 16:48 UTC, coderkill commented
Noted, will do from the next PR, Thanks for the tip!

2024-12-04 08:58 UTC, loicmathieu requested changes

2024-12-04 08:58 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/runners/pebble/functions/RandomNumberGenerator.java
> +public class RandomNumberGenerator implements Function {
```suggestion
public class RandomNumberFunction implements Function {
```

2024-12-04 08:58 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/runners/pebble/functions/RandomNumberGenerator.java
> +public class RandomNumberGenerator implements Function {
We always ends Function class with `Function`

2024-12-04 08:59 UTC, loicmathieu commented
I think it can even be named `RandomFunction` and bind to `random()`.

I wonder if we would need a random float at some time, WDYT @anna-geller ?

2024-12-04 09:02 UTC, coderkill commented on core/src/main/java/io/kestra/core/runners/pebble/functions/RandomNumberGenerator.java
> +public class RandomNumberGenerator implements Function {
Noted! will make change accordingly

2024-12-04 10:25 UTC, anna-geller commented
@loicmathieu no use case for float for now, but given it's named `randomNumber()`, we can add randomFloat if needed later

we need this one for use cases like https://github.com/kestra-io/kestra/issues/5983#issuecomment-2508030834

 LGTM, we can merge as is!

2024-12-04 10:26 UTC, anna-geller approved these changes
thanks for adding this!

2024-12-04 10:54 UTC, loicmathieu commented
@anna-geller well, a float is a number that's why I asked, maybe rename it `randomInt()` ?

2024-12-04 11:48 UTC, coderkill commented
> @anna-geller well, a float is a number that's why I asked, maybe rename it `randomInt()` ?

Do you want me to make this change?

2024-12-04 11:51 UTC, anna-geller commented
np, `randomInt()` works too!

2024-12-04 12:08 UTC, loicmathieu approved these changes
LGMT, thanks a lot

2024-12-04 13:00 UTC, merged