Added a Pebble function [uniq] to deduplice array #6417
kestra-io/kestra pull request #6459
Opened 2024-12-13 17:55 UTC by Rajarajan985

Add a Pebble function [uniq] to deduplice array in the code to convert duplicate value to unique values
[1,2,2,3] | uniq -> [1,2,3]

Added new file:
core/src/main/java/io/kestra/core/runners/pebble/filters/UniqFilter.java

Changes added in existing file:
core/src/main/java/io/kestra/core/docs/DocumentationGenerator.java

2024-12-15 17:45 UTC, Rajarajan985 commented
Hi @loicmathieu  @MilosPaunovic ,
I made the changes for the to remove the duplicate values in the list
can check, is there any changes are required for this code

2024-12-16 07:37 UTC, MilosPaunovic commented
@Rajarajan985 Can you add a test for this?

2024-12-17 16:02 UTC, Rajarajan985 commented
> @Rajarajan985 Can you add a test for this?

@MilosPaunovic I'm working on it.

2024-12-17 17:07 UTC, Rajarajan985 commented
Hi @MilosPaunovic,
Added the test case for uniqFIlter, Can you verify once. 
It is taking mush time to execute this command in my system "gradle test --tests "UniqFilterTest" (Can you describe how to verify test case are working fine)
May I know below mentioned files i haved to add anything related to uniqFilter function
index.peb, macro.peb, task.peb these are available in the pebbleEnigne adding funtionality.

2024-12-17 19:33 UTC, MilosPaunovic commented
@loicmathieu is the one which will review this PR, when he gets the chance.

2024-12-20 10:44 UTC, loicmathieu requested changes

2024-12-20 10:44 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/runners/pebble/filters/UniqFilter.java
> +        return input;
You should throw a `PebbleException` here as we prefer to be strict

2024-12-20 10:44 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/runners/pebble/filters/UniqFilter.java
> +    public Object apply(Object input, Map<String, Object> args, PebbleTemplate self, EvaluationContext context,
If the input is null, please return null to avoid possible NullPointerException.

2024-12-20 10:44 UTC, loicmathieu commented on core/src/test/java/io/kestra/core/runners/pebble/filters/UniqFilterTest.java
We use our variable renderer to test functions closer to how we use them.
You can take as inspiration for ex io.kestra.core.runners.pebble.filters.ToJsonFilterTest

2024-12-20 11:16 UTC, loicmathieu commented
Please also rename the filter to `distinct`.

2024-12-21 18:39 UTC, Rajarajan985 commented on core/src/test/java/io/kestra/core/runners/pebble/filters/UniqFilterTest.java
@loicmathieu Yes sure, I'm working on it.

2024-12-22 11:07 UTC, Rajarajan985 commented
@loicmathieu I have made the changes.
While running the test cases getting this below exception Filter [distinct] does not exist.. 
Can you help me to sort out this issue.

2024-12-22 16:15:20,433 ERROR Test worker  io.kestra.core.secret.SecretService Could not decode secret 'SECRET_NON_B64_SECRET', make sure it is Base64-encoded: Illegal base64 character 20
Before applying distinct filter : ["one","two","one","three","four","five","three",1,2,3,1,2,2,1.123,2.123,1.123,10.0,10.0]

io.pebbletemplates.pebble.error.PebbleException: Filter [distinct] does not exist. ({{ vars.second.list | distinct }}:1)
io.kestra.core.exceptions.IllegalVariableEvaluationException: io.pebbletemplates.pebble.error.PebbleException: Filter [distinct] does not exist. ({{ vars.second.list | distinct }}:1)
	at io.kestra.core.runners.VariableRenderer.properPebbleException(VariableRenderer.java:64)
	at io.kestra.core.runners.VariableRenderer.renderOnce(VariableRenderer.java:120)
	at io.kestra.core.runners.VariableRenderer.render(VariableRenderer.java:91)
	at io.kestra.core.runners.VariableRenderer.render(VariableRenderer.java:76)
	at io.kestra.core.runners.VariableRenderer.render(VariableRenderer.java:68)
	at io.kestra.core.runners.pebble.filters.DistinctFilterTest.toDistinctFilter(DistinctFilterTest.java:62)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.micronaut.test.extensions.junit5.MicronautJunit5Extension$2.proceed(MicronautJunit5Extension.java:142)
	at io.micronaut.test.extensions.AbstractMicronautExtension.interceptEach(AbstractMicronautExtension.java:162)
	at io.micronaut.test.extensions.AbstractMicronautExtension.interceptTest(AbstractMicronautExtension.java:119)
	at io.micronaut.test.extensions.junit5.MicronautJunit5Extension.interceptTestMethod(MicronautJunit5Extension.java:129)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: io.pebbletemplates.pebble.error.PebbleException: Filter [distinct] does not exist. ({{ vars.second.list | distinct }}:1)
	at io.pebbletemplates.pebble.node.expression.FilterExpression.evaluate(FilterExpression.java:49)
	at io.pebbletemplates.pebble.node.PrintNode.render(PrintNode.java:37)
	at io.pebbletemplates.pebble.node.BodyNode.render(BodyNode.java:44)
	at io.pebbletemplates.pebble.node.RootNode.render(RootNode.java:31)
	at io.pebbletemplates.pebble.template.PebbleTemplateImpl.evaluate(PebbleTemplateImpl.java:157)
	at io.pebbletemplates.pebble.template.PebbleTemplateImpl.evaluate(PebbleTemplateImpl.java:96)
	at io.kestra.core.runners.VariableRenderer.renderOnce(VariableRenderer.java:114)
	... 11 more


Filter [distinct] does not exist. ({{ vars.second.list | distinct }}:1)
io.pebbletemplates.pebble.error.PebbleException: Filter [distinct] does not exist. ({{ vars.second.list | distinct }}:1)
	at app//io.pebbletemplates.pebble.node.expression.FilterExpression.evaluate(FilterExpression.java:49)
	at app//io.pebbletemplates.pebble.node.PrintNode.render(PrintNode.java:37)
	at app//io.pebbletemplates.pebble.node.BodyNode.render(BodyNode.java:44)
	at app//io.pebbletemplates.pebble.node.RootNode.render(RootNode.java:31)
	at app//io.pebbletemplates.pebble.template.PebbleTemplateImpl.evaluate(PebbleTemplateImpl.java:157)
	at app//io.pebbletemplates.pebble.template.PebbleTemplateImpl.evaluate(PebbleTemplateImpl.java:96)
	at app//io.kestra.core.runners.VariableRenderer.renderOnce(VariableRenderer.java:114)
	at app//io.kestra.core.runners.VariableRenderer.render(VariableRenderer.java:91)
	at app//io.kestra.core.runners.VariableRenderer.render(VariableRenderer.java:76)
	at app//io.kestra.core.runners.VariableRenderer.render(VariableRenderer.java:68)
	at app//io.kestra.core.runners.pebble.filters.DistinctFilterTest.toDistinctFilter(DistinctFilterTest.java:62)
	at java.base@21.0.5/java.lang.reflect.Method.invoke(Method.java:580)
	at app//io.micronaut.test.extensions.junit5.MicronautJunit5Extension$2.proceed(MicronautJunit5Extension.java:142)
	at app//io.micronaut.test.extensions.AbstractMicronautExtension.interceptEach(AbstractMicronautExtension.java:162)
	at app//io.micronaut.test.extensions.AbstractMicronautExtension.interceptTest(AbstractMicronautExtension.java:119)
	at app//io.micronaut.test.extensions.junit5.MicronautJunit5Extension.interceptTestMethod(MicronautJunit5Extension.java:129)
	at java.base@21.0.5/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base@21.0.5/java.util.ArrayList.forEach(ArrayList.java:1596)

2024-12-22 12:00 UTC, Rajarajan985 commented
@loicmathieu I have made the all the changes.
Now test cases are passed.
Can you verify at your end once.

Please find the below test case passed screenshot for your reference.
![Capture](https://github.com/user-attachments/assets/7b668529-37ea-481f-bd60-03d2761f3fd4)

2024-12-23 08:11 UTC, loicmathieu requested changes

2024-12-23 08:11 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/runners/pebble/filters/DistinctFilter.java
> +                        int lineNumber) throws PebbleException, NullPointerException {
```suggestion
                        int lineNumber) throws PebbleException {
```

Please don't declare throws NullPointerException, NPE are always considered as a bug.

2024-12-23 08:11 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/runners/pebble/filters/DistinctFilter.java
Can you allow null on this filter?

Please add this in the beginning of the method:

```java
        if (input == null) {
            return null;
        }
```

2024-12-23 08:11 UTC, loicmathieu commented on core/src/test/java/io/kestra/core/runners/pebble/filters/DistinctFilterTest.java
> +        System.out.println("Before applying distinct filter : " + render);
```suggestion
```

2024-12-23 08:11 UTC, loicmathieu commented on core/src/test/java/io/kestra/core/runners/pebble/filters/DistinctFilterTest.java
> +        System.out.println("After applying distinct filter : " + distinctRender);
```suggestion
```

2024-12-23 13:38 UTC, Rajarajan985 commented
@loicmathieu I have made the changes. Can you verify once

2024-12-23 13:42 UTC, loicmathieu commented on core/src/test/java/io/kestra/core/runners/pebble/filters/DistinctFilterTest.java
> +    void distinctFilterWithNullInput() {
I think this test will now pass.

2024-12-23 13:42 UTC, loicmathieu approved these changes
LGTM, thanks a lot.

2024-12-23 14:23 UTC, Rajarajan985 commented
@loicmathieu Some check were unsuccessful
Can you check, is there any changes I have to make

2024-12-23 14:26 UTC, loicmathieu commented on core/src/test/java/io/kestra/core/runners/pebble/filters/DistinctFilterTest.java
> +    void distinctFilterWithNullInput() {
I was not clear, this test would not pass as null is allowed.
Can you update the test so we can merge?

2024-12-23 15:09 UTC, loicmathieu commented
@Rajarajan96597 yes, the test `distinctFilterWithNullInput` is now wrong as it assert that an exception is thrown but as we return null for null parameter it no longer throws an exception, please update the test accordingly

2024-12-23 15:36 UTC, Rajarajan985 commented
@loicmathieu Done the changes for the test cases.
Can you verify the test case once.

2024-12-23 15:44 UTC, Rajarajan985 commented
@loicmathieu At my end have to raise any merge request for this code like "Update with merge commit" or "Update with rebase" to commit code in the branch

2024-12-24 08:32 UTC, loicmathieu approved these changes

2024-12-24 09:01 UTC, merged