chore(tasks): improve unit test of http tasks
kestra-io/kestra pull request #6551
Opened 2024-12-20 23:35 UTC by tchiotludo

2024-12-31 15:07 UTC, loicmathieu requested changes

2024-12-31 15:07 UTC, loicmathieu commented on core/src/main/java/io/kestra/plugin/core/http/AbstractHttp.java
> -    protected HttpMethod method = HttpMethod.GET;
It would be better to have an enumeration for the method, this allows validation and avoid any isuse

2024-12-31 15:07 UTC, loicmathieu commented on core/src/main/java/io/kestra/plugin/core/http/Trigger.java
> +    private Boolean allowFailed = false;
This is strange to have allowFailed on the top level here and on the option for other tasks.
I would prefer to keep it on the top level for all cases, this is not an HttpOption but an implementation detail for the HTTP plugin tasks and triggers (other task may not want to allow failed request)

2024-12-31 15:07 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/http/HttpResponse.java
> +    public static class EndpointDetail {
I'm not sure we really need to expose all those information, I cannot find any use case of it.
I think it would be better to lower the API surface and add more things later if needed.

2024-12-31 15:07 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/http/client/HttpClient.java
> +        }
I'm not fan of this kind of lazy construction, it opens the door to concurrent programming bugs and complicate the programming model.

As this is designed to be used inside a task in a try-with-resource block, I would create the client inside the constructor so it can be used as a regular (non transient) attribute.

2024-12-31 15:07 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/http/client/HttpClient.java
> +                builder.setDefaultCredentialsProvider(credentialsProvider);
This seems odd, you create a credential provider for the proxy and set it as the default?

Also, it didn't support basic/token auth?

2024-12-31 15:07 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/http/client/HttpClient.java
It may be handy to have access to the underlying Http Client (I already think of one usage).

If you don't want to expose the Apache client, you can have an `unwrap(Class)` method, this is pretty standard, it would hide the Apache client class but still allow to get access to it if needed.

2024-12-31 15:07 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/http/client/configurations/AbstractAuthConfiguration.java
> +    @JsonSubTypes.Type(value = BasicAuthConfiguration.class, name = "BASICAUTH"),
```suggestion
    @JsonSubTypes.Type(value = BasicAuthConfiguration.class, name = "BASIC"),
```

The standard name is BASIC not BASICAUTH

2024-12-31 15:07 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/http/client/configurations/BasicAuthConfiguration.java
> +    protected String type = "BASICAUTH";
```suggestion
    protected String type = "BASIC";
```

2024-12-31 15:07 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/http/client/configurations/AbstractAuthConfiguration.java
> +    @JsonSubTypes.Type(value = BasicAuthConfiguration.class, name = "BASICAUTH"),
An enum would be great here also, to allow validation

2024-12-31 15:07 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/http/client/configurations/BearerAuthConfiguration.java
> +    @Schema(title = "The password for HTTP basic authentication.")
```suggestion
    @Schema(title = "The token for bearer token authentication.")
```

2024-12-31 15:07 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/http/client/configurations/HttpConfiguration.java
I'm not sure all those `@Deprecated set*()` method will disaply the deprecation warning, I think that as there is no corresponding getter the warning will not be displayed.

2024-12-31 15:21 UTC, nkwiatkowski commented on core/src/main/java/io/kestra/core/http/client/apache/AbstractLoggingInterceptor.java
> +            );
This will log Authorization tokens (like bearer, basic...). I think a header blacklist should be used to remove of censure headers from the logs

2024-12-31 15:21 UTC, nkwiatkowski commented on core/src/main/java/io/kestra/core/http/client/apache/AbstractLoggingInterceptor.java
> +            return type + " payload: null";
Same here, the body can contain sensitive information

2024-12-31 15:21 UTC, nkwiatkowski commented on core/src/main/java/io/kestra/core/http/client/apache/FailedResponseInterceptor.java
> +            String error = "Failed http request with response code '" + response.getCode() + "'";
I don't know if it has to be done like that, but I am used to have a client return null for 404 status instead of exception.

2024-12-31 15:24 UTC, tchiotludo commented on core/src/main/java/io/kestra/plugin/core/http/AbstractHttp.java
> -    protected HttpMethod method = HttpMethod.GET;
I discovered that the previous implementation don't allow custom method, and it's part of the http specs to let people respond on any method (even custom one). 
I didn't see any way for now to have enum + custom method. 
Any idea?

2024-12-31 15:29 UTC, tchiotludo commented on core/src/main/java/io/kestra/core/http/client/apache/FailedResponseInterceptor.java
> +            String error = "Failed http request with response code '" + response.getCode() + "'";
It's was the behavior of Micronaut client, and I found it better and safer, any response code >= 400 need a special behavior to be catch, exception is explicit, validating response code on each call can be bug prone

2024-12-31 15:45 UTC, nkwiatkowski commented on core/src/main/java/io/kestra/plugin/core/http/AbstractHttp.java
> -    protected HttpMethod method = HttpMethod.GET;
Can't we just use an enum there, and the client convert it to string when used ?

2024-12-31 17:23 UTC, loicmathieu commented on core/src/main/java/io/kestra/core/http/client/apache/FailedResponseInterceptor.java
> +            String error = "Failed http request with response code '" + response.getCode() + "'";
I'm also for returning null for 404.

As far as I remember, this was why we added a special boolean to allowEmptyResponse to return null, to bypass 404 throwing an exception.

2024-12-31 17:24 UTC, loicmathieu commented on core/src/main/java/io/kestra/plugin/core/http/AbstractHttp.java
> -    protected HttpMethod method = HttpMethod.GET;
You can use String as the property, an enum where you use `.name()` to convert it to String.
But it may not provide any benefit after all.

2025-01-01 21:16 UTC, tchiotludo commented on core/src/main/java/io/kestra/core/http/client/HttpClient.java
> +                builder.setDefaultCredentialsProvider(credentialsProvider);
good catch, fixed

2025-01-01 21:16 UTC, tchiotludo commented on core/src/main/java/io/kestra/core/http/client/HttpClient.java
It's totally the goal to not expose the based http client (to be able to change in a future if needed)

2025-01-01 21:18 UTC, tchiotludo commented on core/src/main/java/io/kestra/core/http/HttpResponse.java
> +    public static class EndpointDetail {
it give the endpoint (the real ip) available on the log and it exposed a lot of metrics that is available on the kestra context (send & received bytes), could be useful with the new dashboard implementation

2025-01-01 21:19 UTC, tchiotludo commented on core/src/main/java/io/kestra/plugin/core/http/Trigger.java
> +    private Boolean allowFailed = false;
good catch, it's removed since not needed and forced to true

2025-01-01 21:22 UTC, tchiotludo commented on core/src/main/java/io/kestra/core/http/client/apache/AbstractLoggingInterceptor.java
> +            );
Part of the trade-off, it's : 
- disabled by default
- when enabled
  - will be masked if it's a secret, like any secret on logs
  - will be visible if not, I will prefer to keep the option to display these one if people enable manually the log (instead of masking all the time) to empower debugging experience

2025-01-01 21:23 UTC, tchiotludo commented on core/src/main/java/io/kestra/core/http/client/apache/AbstractLoggingInterceptor.java
> +            return type + " payload: null";
same here, impossible to know what could be hidden, but it's a manual feature flags, responsibility of the flow owner

2025-01-02 13:01 UTC, tchiotludo commented on core/src/main/java/io/kestra/core/http/client/apache/FailedResponseInterceptor.java
> +            String error = "Failed http request with response code '" + response.getCode() + "'";
I'm stronglmy against changing this behavior, it's a breaking change, and people need to manage the error, we couldn't let them failed silently.

2025-01-02 14:53 UTC, tchiotludo commented on core/src/main/java/io/kestra/core/http/client/HttpClient.java
> +        }
fixed

2025-01-02 14:53 UTC, tchiotludo commented on core/src/main/java/io/kestra/core/http/client/configurations/HttpConfiguration.java
fixed

2025-01-02 17:11 UTC, merged