fix(ui):Added loading screens instead of no data
kestra-io/kestra pull request #6602
Opened 2024-12-29 19:42 UTC by Karthik73965

Closes #6469

Instead of showing 0 (zeor's)  initially while fetching the data now loading screen are being shown in the dashboard . 

https://github.com/user-attachments/assets/a6a5e50e-ce30-4487-aa69-8f1619539d5b

2024-12-30 09:54 UTC, MilosPaunovic requested changes
This is a good approach, but we'd actually like to have entire cards being replace by loading skeletons from [Element Plus](https://element-plus.org/en-US/component/skeleton). Could you do that change before I review it again @Karthik73965?

2024-12-30 10:22 UTC, Karthik73965 commented
I had few queries  . 

1 .Should the entire card, including the name, be replaced with loading skeletons?
2 .Do we need to implement this for the entire dashboard?

Will do the changes once clarified ! @MilosPaunovic

2024-12-30 10:23 UTC, MilosPaunovic commented
Yes, every card separately, and yes, we can do it for the entire dashboard (all cards).

2025-01-16 11:16 UTC, MilosPaunovic commented
@Karthik73965 Is there any progress on this?

2025-02-04 12:49 UTC, MilosPaunovic approved these changes

2025-02-04 12:56 UTC, merged